# STATE_ Data Transformation

Task: use Pandas to transform csv files into DataFrames that match desired tables for database schema

Tables:

- STATE_CONTIGUITY (done)
- STATE_RESOURCE (done)

In [1]:
import pandas as pd
import numpy as np

In [2]:
!ls ../SourceData/CorrelatesOfWar/

Codebooks                    MID_Narratives_2002-2010.pdf
CowWarList.csv               NMC_5_0-wsupplementary.csv
CowWarList.pdf               Non-StateWarData_v4.0.csv
Entities.pdf                 Territories.csv
Extra-StateWarData_v4.0.csv  alliance_v4.1_by_member.csv
IGO_stateunit_v2.3.csv       contdir.csv
Inter-StateWarData_v4.0.csv  igounit_v2.3.csv
Intra-StateWarData_v4.1.csv  majors2016.csv
MIDA_4.2.csv                 states2016.csv
MIDB_4.2.csv                 system2016.csv
MIDLOCA_2.0.csv              tc2014.csv
MID_Narratives_1993-2001.pdf

## Create 'STATE_CONTIGUITY' table

Task: transform contdir.csv into a table with attributes:

- StateA
- StateB
- StartDate
- EndDate
- StartYear
- StartMonth
- EndYear
- EndMonth
- Type
- Notes

In [3]:
dfStateCont = pd.read_csv('../SourceData/CorrelatesOfWar/contdir.csv')
dfStateCont

,dyad,statelno,statelab,statehno,statehab,conttype,begin,end,notes,version
0,2020,2,USA,20,CAN,1,192001,201612,Begins with CAN system entry,3.2
1,2031,2,USA,31,BHM,4,197307,201612,Across Atlantic Ocean (closest=Florida-Bimini)...,3.2
2,2040,2,USA,40,CUB,4,190205,190609,Across Florida Straits (closest=Key West); beg...,3.2
3,2040,2,USA,40,CUB,4,190901,201612,Across Florida Straits (closest=Key West); res...,3.2
4,2070,2,USA,70,MEX,1,183101,201612,Begins with MEX system entry,3.2
5,2365,2,USA,365,RUS,2,195901,201612,Across Bering Strait (closest=Alaska-Siberia);...,3.2
6,31040,31,BHM,40,CUB,4,197307,201612,Across Atlantic Ocean (closest=Great Inagua); ...,3.2
7,31041,31,BHM,41,HAI,4,197307,201612,Across Atlantic Ocean (closest=Great Inagua); ...,3.2
8,31042,31,BHM,42,DOM,4,197307,201612,Across Atlantic Ocean (closest=Great Inagua); ...,3.2
9,31051,31,BHM,51,JAM,5,197307,201612,Across Windward Passage (closest=Great Inagua)...,3.2
10,40041,40,CUB,41,HAI,4,190205,190609,Across Windward Passage; begins with CUB syste...,3.2
11,40041,40,CUB,41,HAI,4,190901,191507,Across Windward Passage; resumes after USA occ...,3.2
12,40041,40,CUB,41,HAI,4,193408,201612,Across Windward Passage; resumes after USA occ...,3.2
13,40042,40,CUB,42,DOM,5,190205,190609,Across Windward Passage (closest=Great Inagua)...,3.2
14,40042,40,CUB,42,DOM,5,190901,191611,Across Windward Passage; resumes after USA occ...,3.2
15,40042,40,CUB,42,DOM,5,192409,201612,Across Windward Passage; resumes after USA occ...,3.2
16,40051,40,CUB,51,JAM,4,196208,201612,Across Caribbean Sea; begins with JAM system e...,3.2
17,40070,40,CUB,70,MEX,4,190205,190609,Across Yucatan Channel; begins with CUB system...,3.2
18,40070,40,CUB,70,MEX,4,190901,201612,Across Yucatan Channel; resumes after USA occu...,3.2
19,40080,40,CUB,80,BLZ,5,198109,201612,Across Caribbean Sea; begins with BLZ system e...,3.2
20,40091,40,CUB,91,HON,5,190205,190609,Across Caribbean Sea; begins with CUB system e...,3.2
21,40091,40,CUB,91,HON,5,190901,201612,Across Caribbean Sea; resumes after USA occupa...,3.2
22,41042,41,HAI,42,DOM,1,189401,191507,Begins with DOM system entry; ends with USA oc...,3.2
23,41042,41,HAI,42,DOM,1,193408,201612,Resumes after USA occupation of HAI ends,3.2
24,41051,41,HAI,51,JAM,4,196208,201612,Across Jamaica Channel; begins with JAM system...,3.2
25,41100,41,HAI,100,COL,5,185901,191507,Across Caribbean Sea; begins with HAI system e...,3.2
26,41100,41,HAI,100,COL,5,193408,201612,Across Caribbean Sea; resumes after USA occupa...,3.2
27,42051,42,DOM,51,JAM,5,196208,201612,Across Jamaica Channel/Caribbean Sea; begins w...,3.2
28,42060,42,DOM,60,SKN,5,198309,201612,Across Caribbean Sea; begins with SKN system e...,3.2
29,42100,42,DOM,100,COL,5,189401,191611,Across Caribbean Sea; begins with DOM system e...,3.2
...,...,...,...,...,...,...,...,...,...,...
817,816850,816,DRV,850,INS,5,197504,201612,Across South China Sea (through S.Vietnam); be...,3.2
818,817820,817,RVN,820,MAL,5,195708,197504,Across South China Sea; begins with MAL system...,3.2
819,817850,817,RVN,850,INS,5,195406,197504,Across Gulf of Thailand; begins with RVN syste...,3.2
820,820830,820,MAL,830,SIN,1,196508,201612,Begins with SIN system entry,3.2
821,820835,820,MAL,835,BRU,1,198401,201612,Begins with BRU system etry,3.2
822,820840,820,MAL,840,PHI,3,196309,201612,Across Balabac Strait (through Sabah-Palawan);...,3.2
823,820850,820,MAL,850,INS,3,195708,196309,Across Strait of Malacca (through Sumatra-Mala...,3.2
824,820850,820,MAL,850,INS,1,196309,201612,Begins when Sabah/Sarawak join MAL,3.2
825,830850,830,SIN,850,INS,2,196508,201612,Across Singapore Strait; begins with SIN syste...,3.2
826,835840,835,BRU,840,PHI,5,198401,201612,Across South China Sea (through Palawan); begi...,3.2
827,840850,840,PHI,850,INS,4,194912,201612,Across Celebes Sea (through Sulu Archipelago-B...,3.2
828,840986,840,PHI,986,PAL,5,199411,201612,Across Pacific Ocean; begins with PAL system e...,3.2
829,850860,850,INS,860,ETM,1,200209,201612,Begins with ETM system entry,3.2
830,850900,850,INS,900,AUL,5,194912,196304,Across Timor Sea (through Timor); begins with ...,3.2
831,850900,850,INS,900,AUL,4,196305,201612,Across Arafura Sea (through Irian Jaya); begin...,3.2
832,850910,850,INS,910,PNG,1,197509,201612,Begins with PNG system entry,3.2
833,850986,850,INS,986,PAL,4,199411,201612,Across Pacific Ocean; begins with PAL system e...,3.2
834,850987,850,INS,987,FSM,5,199109,201612,Across Pacific Ocean; begins with FSM system e...,3.2
835,860900,860,ETM,900,AUL,5,200209,201612,Across Timor Sea; begins with ETM system entry,3.2
836,900910,900,AUL,910,PNG,2,197509,201612,Across Torres Strait; begins with PNG system e...,3.2
837,910940,910,PNG,940,SOL,2,197807,201612,Across Solomon Sea; begins with SOL system entry,3.2
838,910987,910,PNG,987,FSM,5,199109,201612,Across Pacific Ocean; begins with FSM system e...,3.2
839,935940,935,VAN,940,SOL,4,198109,201612,Across Pacific Ocean; begins with VAN system e...,3.2
840,946947,946,KIR,947,TUV,5,200008,201612,Across Pacific Ocean; begins with TUV system e...,3.2
841,946970,946,KIR,970,NAU,5,199909,201612,Across Pacific Ocean; begins with KIR and NAU ...,3.2
842,946983,946,KIR,983,MSI,5,199909,201612,Across Pacific Ocean; begins with KIR system e...,3.2
843,947950,947,TUV,950,FIJ,5,200008,201612,Across Pacific Ocean; begins with TUV system e...,3.2
844,950955,950,FIJ,955,TON,5,199908,201612,Across Pacific Ocean; begins with TON system e...,3.2
845,955990,955,TON,990,WSM,5,199908,201612,Across Pacific Ocean; begins with TON system e...,3.2
846,986987,986,PAL,987,FSM,4,199411,201612,Across Pacific Ocean; begins with PAL system e...,3.2

In [4]:
dfStateCont.rename(columns={"statelno":"StateA", "statehno": "StateB", "conttype":"Type", "notes":"Notes"}, inplace=True)
dfStateCont['StartYear'] = dfStateCont['begin'].astype(str).str[0:4]
dfStateCont['StartMonth'] = dfStateCont['begin'].astype(str).str[4:6]
dfStateCont['EndYear'] = dfStateCont['end'].astype(str).str[0:4]
dfStateCont['EndMonth'] = dfStateCont['end'].astype(str).str[4:6]
dfStateCont.drop(columns=['dyad', 'statelab', 'statehab', 'version', 'begin', 'end'], inplace=True)

dfStateCont['StartDate'] = pd.to_datetime(dict(year=dfStateCont.StartYear, month=dfStateCont.StartMonth, day='01'))
dfStateCont['EndDate'] = pd.to_datetime(dict(year=dfStateCont.EndYear, month=dfStateCont.EndMonth, day='01'))
dfStateCont['StartDate'] = dfStateCont['StartDate'].apply(lambda x: x.strftime('%Y-%m-%d'))
dfStateCont['EndDate'] = dfStateCont['EndDate'].apply(lambda x: x.strftime('%Y-%m-%d'))

dfStateCont = dfStateCont[['StateA', 'StateB', 'StartDate', 'EndDate', 'StartYear', 'StartMonth', 'EndYear', 'EndMonth', 'Type', 'Notes']]
dfStateCont

,StateA,StateB,StartDate,EndDate,StartYear,StartMonth,EndYear,EndMonth,Type,Notes
0,2,20,1920-01-01,2016-12-01,1920,01,2016,12,1,Begins with CAN system entry
1,2,31,1973-07-01,2016-12-01,1973,07,2016,12,4,Across Atlantic Ocean (closest=Florida-Bimini)...
2,2,40,1902-05-01,1906-09-01,1902,05,1906,09,4,Across Florida Straits (closest=Key West); beg...
3,2,40,1909-01-01,2016-12-01,1909,01,2016,12,4,Across Florida Straits (closest=Key West); res...
4,2,70,1831-01-01,2016-12-01,1831,01,2016,12,1,Begins with MEX system entry
5,2,365,1959-01-01,2016-12-01,1959,01,2016,12,2,Across Bering Strait (closest=Alaska-Siberia);...
6,31,40,1973-07-01,2016-12-01,1973,07,2016,12,4,Across Atlantic Ocean (closest=Great Inagua); ...
7,31,41,1973-07-01,2016-12-01,1973,07,2016,12,4,Across Atlantic Ocean (closest=Great Inagua); ...
8,31,42,1973-07-01,2016-12-01,1973,07,2016,12,4,Across Atlantic Ocean (closest=Great Inagua); ...
9,31,51,1973-07-01,2016-12-01,1973,07,2016,12,5,Across Windward Passage (closest=Great Inagua)...
10,40,41,1902-05-01,1906-09-01,1902,05,1906,09,4,Across Windward Passage; begins with CUB syste...
11,40,41,1909-01-01,1915-07-01,1909,01,1915,07,4,Across Windward Passage; resumes after USA occ...
12,40,41,1934-08-01,2016-12-01,1934,08,2016,12,4,Across Windward Passage; resumes after USA occ...
13,40,42,1902-05-01,1906-09-01,1902,05,1906,09,5,Across Windward Passage (closest=Great Inagua)...
14,40,42,1909-01-01,1916-11-01,1909,01,1916,11,5,Across Windward Passage; resumes after USA occ...
15,40,42,1924-09-01,2016-12-01,1924,09,2016,12,5,Across Windward Passage; resumes after USA occ...
16,40,51,1962-08-01,2016-12-01,1962,08,2016,12,4,Across Caribbean Sea; begins with JAM system e...
17,40,70,1902-05-01,1906-09-01,1902,05,1906,09,4,Across Yucatan Channel; begins with CUB system...
18,40,70,1909-01-01,2016-12-01,1909,01,2016,12,4,Across Yucatan Channel; resumes after USA occu...
19,40,80,1981-09-01,2016-12-01,1981,09,2016,12,5,Across Caribbean Sea; begins with BLZ system e...
20,40,91,1902-05-01,1906-09-01,1902,05,1906,09,5,Across Caribbean Sea; begins with CUB system e...
21,40,91,1909-01-01,2016-12-01,1909,01,2016,12,5,Across Caribbean Sea; resumes after USA occupa...
22,41,42,1894-01-01,1915-07-01,1894,01,1915,07,1,Begins with DOM system entry; ends with USA oc...
23,41,42,1934-08-01,2016-12-01,1934,08,2016,12,1,Resumes after USA occupation of HAI ends
24,41,51,1962-08-01,2016-12-01,1962,08,2016,12,4,Across Jamaica Channel; begins with JAM system...
25,41,100,1859-01-01,1915-07-01,1859,01,1915,07,5,Across Caribbean Sea; begins with HAI system e...
26,41,100,1934-08-01,2016-12-01,1934,08,2016,12,5,Across Caribbean Sea; resumes after USA occupa...
27,42,51,1962-08-01,2016-12-01,1962,08,2016,12,5,Across Jamaica Channel/Caribbean Sea; begins w...
28,42,60,1983-09-01,2016-12-01,1983,09,2016,12,5,Across Caribbean Sea; begins with SKN system e...
29,42,100,1894-01-01,1916-11-01,1894,01,1916,11,5,Across Caribbean Sea; begins with DOM system e...
...,...,...,...,...,...,...,...,...,...,...
817,816,850,1975-04-01,2016-12-01,1975,04,2016,12,5,Across South China Sea (through S.Vietnam); be...
818,817,820,1957-08-01,1975-04-01,1957,08,1975,04,5,Across South China Sea; begins with MAL system...
819,817,850,1954-06-01,1975-04-01,1954,06,1975,04,5,Across Gulf of Thailand; begins with RVN syste...
820,820,830,1965-08-01,2016-12-01,1965,08,2016,12,1,Begins with SIN system entry
821,820,835,1984-01-01,2016-12-01,1984,01,2016,12,1,Begins with BRU system etry
822,820,840,1963-09-01,2016-12-01,1963,09,2016,12,3,Across Balabac Strait (through Sabah-Palawan);...
823,820,850,1957-08-01,1963-09-01,1957,08,1963,09,3,Across Strait of Malacca (through Sumatra-Mala...
824,820,850,1963-09-01,2016-12-01,1963,09,2016,12,1,Begins when Sabah/Sarawak join MAL
825,830,850,1965-08-01,2016-12-01,1965,08,2016,12,2,Across Singapore Strait; begins with SIN syste...
826,835,840,1984-01-01,2016-12-01,1984,01,2016,12,5,Across South China Sea (through Palawan); begi...
827,840,850,1949-12-01,2016-12-01,1949,12,2016,12,4,Across Celebes Sea (through Sulu Archipelago-B...
828,840,986,1994-11-01,2016-12-01,1994,11,2016,12,5,Across Pacific Ocean; begins with PAL system e...
829,850,860,2002-09-01,2016-12-01,2002,09,2016,12,1,Begins with ETM system entry
830,850,900,1949-12-01,1963-04-01,1949,12,1963,04,5,Across Timor Sea (through Timor); begins with ...
831,850,900,1963-05-01,2016-12-01,1963,05,2016,12,4,Across Arafura Sea (through Irian Jaya); begin...
832,850,910,1975-09-01,2016-12-01,1975,09,2016,12,1,Begins with PNG system entry
833,850,986,1994-11-01,2016-12-01,1994,11,2016,12,4,Across Pacific Ocean; begins with PAL system e...
834,850,987,1991-09-01,2016-12-01,1991,09,2016,12,5,Across Pacific Ocean; begins with FSM system e...
835,860,900,2002-09-01,2016-12-01,2002,09,2016,12,5,Across Timor Sea; begins with ETM system entry
836,900,910,1975-09-01,2016-12-01,1975,09,2016,12,2,Across Torres Strait; begins with PNG system e...
837,910,940,1978-07-01,2016-12-01,1978,07,2016,12,2,Across Solomon Sea; begins with SOL system entry
838,910,987,1991-09-01,2016-12-01,1991,09,2016,12,5,Across Pacific Ocean; begins with FSM system e...
839,935,940,1981-09-01,2016-12-01,1981,09,2016,12,4,Across Pacific Ocean; begins with VAN system e...
840,946,947,2000-08-01,2016-12-01,2000,08,2016,12,5,Across Pacific Ocean; begins with TUV system e...
841,946,970,1999-09-01,2016-12-01,1999,09,2016,12,5,Across Pacific Ocean; begins with KIR and NAU ...
842,946,983,1999-09-01,2016-12-01,1999,09,2016,12,5,Across Pacific Ocean; begins with KIR system e...
843,947,950,2000-08-01,2016-12-01,2000,08,2016,12,5,Across Pacific Ocean; begins with TUV system e...
844,950,955,1999-08-01,2016-12-01,1999,08,2016,12,5,Across Pacific Ocean; begins with TON system e...
845,955,990,1999-08-01,2016-12-01,1999,08,2016,12,5,Across Pacific Ocean; begins with TON system e...
846,986,987,1994-11-01,2016-12-01,1994,11,2016,12,4,Across Pacific Ocean; begins with PAL system e...

In [5]:
NoteMaxLength = int(dfStateCont['Notes'].str.encode(encoding='utf-8').str.len().max())
print('NoteMaxLength:', NoteMaxLength)
dfStateCont.Type.unique()

NoteMaxLength: 163

array([1, 4, 2, 5, 3])

In [6]:
dfStateCont.to_csv('../FinalData/state_contiguity.csv', encoding='utf-8', index=False)

## Create 'STATE_RESOURCE' table

Task: transform NMC_5_0-wsupplementary.csv into a table with attributes:

- StateID
- Year
- ResourceID
- Amount
- Source
- Note
- QualityCode
- AnomalyCode

In [7]:
dfResources = pd.read_csv('../SourceData/CorrelatesOfWar/NMC_5_0-wsupplementary.csv')
dfResources.columns

Index(['statenme', 'stateabb', 'ccode', 'year', 'milex', 'milexsource',
       'milexnote', 'milper', 'milpersource', 'milpernote', 'irst',
       'irstsource', 'irstnote', 'irstqualitycode', 'irstanomalycode', 'pec',
       'pecsource', 'pecnote', 'pecqualitycode', 'pecanomalycode', 'tpop',
       'tpopsource', 'tpopnote', 'tpopqualitycode', 'tpopanomalycode', 'upop',
       'upopsource', 'upopnote', 'upopqualitycode', 'upopanomalycode',
       'upopgrowth', 'upopgrowthsource', 'cinc', 'version'],
      dtype='object')

In [8]:
dfResMilex = dfResources[['ccode', 'year', 'milex', 'milexsource', 'milexnote']] 
dfResMilPer = dfResources[['ccode', 'year', 'milper', 'milpersource', 'milpernote']]
dfResIrst = dfResources[['ccode', 'year', 'irst','irstsource', 'irstnote', 'irstqualitycode', 'irstanomalycode']]
dfResPec = dfResources[['ccode', 'year', 'pec', 'pecsource', 'pecnote', 'pecqualitycode', 'pecanomalycode']]
dfResTpop = dfResources[['ccode', 'year', 'tpop', 'tpopsource', 'tpopnote', 'tpopqualitycode', 'tpopanomalycode']]
dfResUpop = dfResources[['ccode', 'year', 'upop', 'upopsource', 'upopnote', 'upopqualitycode', 'upopanomalycode']]
dfResUpgrowth = dfResources[['ccode', 'year', 'upopgrowth', 'upopgrowthsource']]

In [9]:
dfResMilex['ResourceID'] = 'milex'
dfResMilPer['ResourceID'] = 'milper'
dfResIrst['ResourceID'] = 'irst'
dfResPec['ResourceID'] = 'pec'
dfResTpop['ResourceID'] = 'tpop'
dfResUpop['ResourceID'] = 'upop'
dfResUpgrowth['ResourceID'] = 'upopgrowth'

/usr/local/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/usr/local/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/usr/local/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/usr/local/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
/usr/local/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/usr/local/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [10]:
dfResMilex.rename(columns={'ccode':'StateID', 'year':'Year', 'milex':'Amount', 'milexsource':'Source', 'milexnote':'Note'}, inplace=True)
dfResMilex['QualityCode'] = ''
dfResMilex['AnomalyCode'] = ''
dfResMilex = dfResMilex[['StateID', 'Year', 'ResourceID', 'Amount', 'Source', 'Note', 'QualityCode', 'AnomalyCode']]
dfResMilex

/usr/local/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/usr/local/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/usr/local/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,StateID,Year,ResourceID,Amount,Source,Note,QualityCode,AnomalyCode
0,2,1816,milex,3823,NaN,NaN,,
1,2,1817,milex,2466,NaN,NaN,,
2,2,1818,milex,1910,NaN,NaN,,
3,2,1819,milex,2301,NaN,NaN,,
4,2,1820,milex,1556,NaN,NaN,,
5,2,1821,milex,1612,NaN,NaN,,
6,2,1822,milex,1079,NaN,NaN,,
7,2,1823,milex,1170,NaN,NaN,,
8,2,1824,milex,1261,NaN,NaN,,
9,2,1825,milex,1336,NaN,NaN,,
10,2,1826,milex,1658,NaN,NaN,,
11,2,1827,milex,1663,NaN,NaN,,
12,2,1828,milex,1622,NaN,NaN,,
13,2,1829,milex,1678,NaN,NaN,,
14,2,1830,milex,1687,NaN,NaN,,
15,2,1831,milex,1835,NaN,NaN,,
16,2,1832,milex,1896,NaN,NaN,,
17,2,1833,milex,2445,NaN,NaN,,
18,2,1834,milex,2073,NaN,NaN,,
19,2,1835,milex,2001,NaN,NaN,,
20,2,1836,milex,2571,NaN,NaN,,
21,2,1837,milex,3121,NaN,NaN,,
22,2,1838,milex,3083,NaN,NaN,,
23,2,1839,milex,2012,NaN,NaN,,
24,2,1840,milex,2755,NaN,NaN,,
25,2,1841,milex,3042,NaN,NaN,,
26,2,1842,milex,3011,NaN,NaN,,
27,2,1843,milex,1364,NaN,NaN,,
28,2,1844,milex,2432,NaN,NaN,,
29,2,1845,milex,3534,NaN,NaN,,
...,...,...,...,...,...,...,...,...
15141,990,1983,milex,0,NaN,NaN,,
15142,990,1984,milex,0,NaN,NaN,,
15143,990,1985,milex,0,NaN,NaN,,
15144,990,1986,milex,0,NaN,NaN,,
15145,990,1987,milex,0,NaN,NaN,,
15146,990,1988,milex,0,NaN,NaN,,
15147,990,1989,milex,0,NaN,NaN,,
15148,990,1990,milex,0,NaN,NaN,,
15149,990,1991,milex,0,NaN,NaN,,
15150,990,1992,milex,0,NaN,NaN,,
15151,990,1993,milex,0,NaN,NaN,,
15152,990,1994,milex,0,NaN,Extrapolated - 0,,
15153,990,1995,milex,0,NaN,Extrapolated - 0,,
15154,990,1996,milex,0,NaN,Extrapolated - 0,,
15155,990,1997,milex,0,NaN,Extrapolated - 0,,
15156,990,1998,milex,0,NaN,Extrapolated - 0,,
15157,990,1999,milex,0,NaN,Extrapolated - 0,,
15158,990,2000,milex,0,NaN,Extrapolated - 0,,
15159,990,2001,milex,0,NaN,Extrapolated - 0,,
15160,990,2002,milex,0,IISS/2006,State not coded in Military Balance; CIA WFB r...,,
15161,990,2003,milex,0,IISS/2006,State not coded in Military Balance; CIA WFB r...,,
15162,990,2004,milex,0,IISS/2006,State not coded in Military Balance; CIA WFB r...,,
15163,990,2005,milex,0,IISS/2009,State not coded in Military Balance; CIA WFB r...,,
15164,990,2006,milex,0,IISS/2009,State not coded in Military Balance; CIA WFB r...,,
15165,990,2007,milex,0,IISS/2009,State not coded in Military Balance; CIA WFB r...,,
15166,990,2008,milex,0,IISS/2012,State not coded in Military Balance; CIA WFB r...,,
15167,990,2009,milex,0,IISS/2012,State not coded in Military Balance; CIA WFB r...,,
15168,990,2010,milex,0,IISS/2012,State not coded in Military Balance; CIA WFB r...,,
15169,990,2011,milex,0,IISS/2014,State not coded in Military Balance; CIA WFB r...,,
15170,990,2012,milex,0,IISS/2014,State not coded in Military Balance; CIA WFB r...,,

In [11]:
dfResMilPer.rename(columns={'ccode':'StateID', 'year':'Year', 'milper':'Amount', 'milpersource':'Source', 'milpernote':'Note'}, inplace=True)
dfResMilPer['QualityCode'] = ''
dfResMilPer['AnomalyCode'] = ''
dfResMilPer = dfResMilPer[['StateID', 'Year', 'ResourceID', 'Amount', 'Source', 'Note', 'QualityCode', 'AnomalyCode']]
dfResMilPer

/usr/local/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/usr/local/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/usr/local/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,StateID,Year,ResourceID,Amount,Source,Note,QualityCode,AnomalyCode
0,2,1816,milper,17,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
1,2,1817,milper,15,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
2,2,1818,milper,14,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
3,2,1819,milper,13,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
4,2,1820,milper,15,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
5,2,1821,milper,11,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
6,2,1822,milper,10,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
7,2,1823,milper,11,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
8,2,1824,milper,11,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
9,2,1825,milper,11,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
10,2,1826,milper,12,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
11,2,1827,milper,12,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
12,2,1828,milper,11,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
13,2,1829,milper,12,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
14,2,1830,milper,12,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
15,2,1831,milper,11,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
16,2,1832,milper,12,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
17,2,1833,milper,13,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
18,2,1834,milper,13,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
19,2,1835,milper,14,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
20,2,1836,milper,17,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
21,2,1837,milper,22,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
22,2,1838,milper,18,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
23,2,1839,milper,19,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
24,2,1840,milper,22,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
25,2,1841,milper,21,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
26,2,1842,milper,23,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
27,2,1843,milper,21,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
28,2,1844,milper,21,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
29,2,1845,milper,21,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
...,...,...,...,...,...,...,...,...
15141,990,1983,milper,0,NaN,"Not in ACDA, 1993-94, assumed 0",,
15142,990,1984,milper,0,NaN,"Not in ACDA, 1995, assumed 0",,
15143,990,1985,milper,0,NaN,"Not in ACDA, 1996, assumed 0",,
15144,990,1986,milper,0,NaN,"Not in ACDA, 1996, assumed 0",,
15145,990,1987,milper,0,NaN,"Not in ACDA, 1998, assumed 0",,
15146,990,1988,milper,0,NaN,"Not in ACDA, 1998, assumed 0",,
15147,990,1989,milper,0,NaN,"Not in ACDA, 1998, assumed 0",,
15148,990,1990,milper,0,NaN,"Not in ACDA, 1998, assumed 0",,
15149,990,1991,milper,0,NaN,"Not in ACDA, 1998, assumed 0",,
15150,990,1992,milper,0,NaN,"Not in ACDA, 1998, assumed 0",,
15151,990,1993,milper,0,NaN,"Not in ACDA, 1998, assumed 0",,
15152,990,1994,milper,0,NaN,"Not in ACDA, 1998, assumed 0",,
15153,990,1995,milper,0,NaN,"Not in ACDA, 1998, assumed 0",,
15154,990,1996,milper,0,NaN,"Not in ACDA, 1998, assumed 0",,
15155,990,1997,milper,0,NaN,"Not in ACDA, 1998, assumed 0",,
15156,990,1998,milper,0,NaN,NaN,,
15157,990,1999,milper,0,NaN,NaN,,
15158,990,2000,milper,0,NaN,NaN,,
15159,990,2001,milper,0,NaN,NaN,,
15160,990,2002,milper,0,IISS/2003,State not coded in Military Balance; CIA WFB r...,,
15161,990,2003,milper,0,IISS/2004-5,State not coded in Military Balance; CIA WFB r...,,
15162,990,2004,milper,0,See note.,Military Balance data for MILPER missing in 20...,,
15163,990,2005,milper,0,IISS/2005-6,State not coded in Military Balance; CIA WFB r...,,
15164,990,2006,milper,0,IISS/2006,State not coded in Military Balance; CIA WFB r...,,
15165,990,2007,milper,0,IISS/2007,State not coded in Military Balance; CIA WFB r...,,
15166,990,2008,milper,0,IISS/2008,State not coded in Military Balance; CIA WFB r...,,
15167,990,2009,milper,0,IISS/2009,State not coded in Military Balance; CIA WFB r...,,
15168,990,2010,milper,0,IISS/2010,State not coded in Military Balance; CIA WFB r...,,
15169,990,2011,milper,0,IISS/2011,State not coded in Military Balance; CIA WFB r...,,
15170,990,2012,milper,0,IISS/2012,State not coded in Military Balance; CIA WFB r...,,

In [12]:
dfResUpgrowth.rename(columns={'ccode':'StateID', 'year':'Year', 'upopgrowth':'Amount', 'upopgrowthsource':'Source'}, inplace=True)
dfResUpgrowth['QualityCode'] = ''
dfResUpgrowth['AnomalyCode'] = ''
dfResUpgrowth['Note'] = ''
dfResUpgrowth = dfResUpgrowth[['StateID', 'Year', 'ResourceID', 'Amount', 'Source', 'Note', 'QualityCode', 'AnomalyCode']]
dfResMilPer

/usr/local/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/usr/local/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/usr/local/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

,StateID,Year,ResourceID,Amount,Source,Note,QualityCode,AnomalyCode
0,2,1816,milper,17,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
1,2,1817,milper,15,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
2,2,1818,milper,14,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
3,2,1819,milper,13,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
4,2,1820,milper,15,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
5,2,1821,milper,11,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
6,2,1822,milper,10,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
7,2,1823,milper,11,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
8,2,1824,milper,11,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
9,2,1825,milper,11,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
10,2,1826,milper,12,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
11,2,1827,milper,12,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
12,2,1828,milper,11,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
13,2,1829,milper,12,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
14,2,1830,milper,12,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
15,2,1831,milper,11,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
16,2,1832,milper,12,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
17,2,1833,milper,13,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
18,2,1834,milper,13,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
19,2,1835,milper,14,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
20,2,1836,milper,17,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
21,2,1837,milper,22,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
22,2,1838,milper,18,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
23,2,1839,milper,19,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
24,2,1840,milper,22,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
25,2,1841,milper,21,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
26,2,1842,milper,23,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
27,2,1843,milper,21,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
28,2,1844,milper,21,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
29,2,1845,milper,21,(U.S. Department of Commerce and Bureau of the...,verified 10/22/2001. DLD,,
...,...,...,...,...,...,...,...,...
15141,990,1983,milper,0,NaN,"Not in ACDA, 1993-94, assumed 0",,
15142,990,1984,milper,0,NaN,"Not in ACDA, 1995, assumed 0",,
15143,990,1985,milper,0,NaN,"Not in ACDA, 1996, assumed 0",,
15144,990,1986,milper,0,NaN,"Not in ACDA, 1996, assumed 0",,
15145,990,1987,milper,0,NaN,"Not in ACDA, 1998, assumed 0",,
15146,990,1988,milper,0,NaN,"Not in ACDA, 1998, assumed 0",,
15147,990,1989,milper,0,NaN,"Not in ACDA, 1998, assumed 0",,
15148,990,1990,milper,0,NaN,"Not in ACDA, 1998, assumed 0",,
15149,990,1991,milper,0,NaN,"Not in ACDA, 1998, assumed 0",,
15150,990,1992,milper,0,NaN,"Not in ACDA, 1998, assumed 0",,
15151,990,1993,milper,0,NaN,"Not in ACDA, 1998, assumed 0",,
15152,990,1994,milper,0,NaN,"Not in ACDA, 1998, assumed 0",,
15153,990,1995,milper,0,NaN,"Not in ACDA, 1998, assumed 0",,
15154,990,1996,milper,0,NaN,"Not in ACDA, 1998, assumed 0",,
15155,990,1997,milper,0,NaN,"Not in ACDA, 1998, assumed 0",,
15156,990,1998,milper,0,NaN,NaN,,
15157,990,1999,milper,0,NaN,NaN,,
15158,990,2000,milper,0,NaN,NaN,,
15159,990,2001,milper,0,NaN,NaN,,
15160,990,2002,milper,0,IISS/2003,State not coded in Military Balance; CIA WFB r...,,
15161,990,2003,milper,0,IISS/2004-5,State not coded in Military Balance; CIA WFB r...,,
15162,990,2004,milper,0,See note.,Military Balance data for MILPER missing in 20...,,
15163,990,2005,milper,0,IISS/2005-6,State not coded in Military Balance; CIA WFB r...,,
15164,990,2006,milper,0,IISS/2006,State not coded in Military Balance; CIA WFB r...,,
15165,990,2007,milper,0,IISS/2007,State not coded in Military Balance; CIA WFB r...,,
15166,990,2008,milper,0,IISS/2008,State not coded in Military Balance; CIA WFB r...,,
15167,990,2009,milper,0,IISS/2009,State not coded in Military Balance; CIA WFB r...,,
15168,990,2010,milper,0,IISS/2010,State not coded in Military Balance; CIA WFB r...,,
15169,990,2011,milper,0,IISS/2011,State not coded in Military Balance; CIA WFB r...,,
15170,990,2012,milper,0,IISS/2012,State not coded in Military Balance; CIA WFB r...,,

In [13]:
dfResIrst.rename(columns={'ccode':'StateID', 'year':'Year', 'irst':'Amount', 'irstsource':'Source', 'irstnote':'Note', 'irstqualitycode':'QualityCode', 'irstanomalycode':'AnomalyCode'}, inplace=True)
dfResIrst = dfResIrst[['StateID', 'Year', 'ResourceID', 'Amount', 'Source', 'Note', 'QualityCode', 'AnomalyCode']]
dfResIrst

/usr/local/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

,StateID,Year,ResourceID,Amount,Source,Note,QualityCode,AnomalyCode
0,2,1816,irst,80,"George Routledge and Sons, Limited, 1892, p. ...",COW 1memo states that they interpolated 1816-1...,D,A
1,2,1817,irst,80,"George Routledge and Sons, Limited, 1892, p. ...",COW 1memo states that they interpolated 1816-1...,D,A
2,2,1818,irst,90,"George Routledge and Sons, Limited, 1892, p. ...",COW 1memo states that they interpolated 1816-1...,D,A
3,2,1819,irst,90,"George Routledge and Sons, Limited, 1892, p. ...",COW 1memo states that they interpolated 1816-1...,D,A
4,2,1820,irst,110,"George Routledge and Sons, Limited, 1892, p. ...",COW 1memo states that they interpolated 1816-1...,D,A
5,2,1821,irst,100,"George Routledge and Sons, Limited, 1892, p. ...",p. 264.,D,A
6,2,1822,irst,100,"George Routledge and Sons, Limited, 1892, p. ...",p. 264.,D,A
7,2,1823,irst,110,"George Routledge and Sons, Limited, 1892, p. ...",p. 264.,D,A
8,2,1824,irst,110,"George Routledge and Sons, Limited, 1892, p. ...",p. 264.,D,A
9,2,1825,irst,120,"George Routledge and Sons, Limited, 1892, p. ...",p. 264.,D,A
10,2,1826,irst,120,"George Routledge and Sons, Limited, 1892, p. ...",p. 264.,D,A
11,2,1827,irst,130,"George Routledge and Sons, Limited, 1892, p. ...",p. 264.,D,A
12,2,1828,irst,130,"Temin, Peter. Iron and Stell in the 19th Centu...",NaN,A,A
13,2,1829,irst,144,"4th ed., 1998, p. 359.",NaN,A,A
14,2,1830,irst,168,"4th ed., 1998, p. 359.",NaN,A,A
15,2,1831,irst,194,"4th ed., 1998, p. 359.",NaN,A,A
16,2,1832,irst,203,"4th ed., 1998, p. 359.",NaN,A,A
17,2,1833,irst,220,"Temin, Peter. Iron and Steel in the 19th Centu...",Rounding to the nearest tens.,A,A
18,2,1834,irst,240,"Temin, Peter. Iron and Steel in the 19th Centu...",Rounding to the nearest tens.,A,A
19,2,1835,irst,260,"Temin, Peter. Iron and Steel in the 19th Centu...",Rounding to the nearest tens.,A,A
20,2,1836,irst,280,"Temin, Peter. Iron and Steel in the 19th Centu...",Rounding to the nearest tens.,A,A
21,2,1837,irst,290,"Temin, Peter. Iron and Steel in the 19th Centu...",Rounding to the nearest tens.,A,A
22,2,1838,irst,310,"Temin, Peter. Iron and Steel in the 19th Centu...",Rounding to the nearest tens.,A,A
23,2,1839,irst,330,"Temin, Peter. Iron and Steel in the 19th Centu...",Rounding to the nearest tens.,A,A
24,2,1840,irst,291,"4th ed., 1998, p. 359.",NaN,A,A
25,2,1841,irst,290,"Temin, Peter. Iron and Steel in the 19th Centu...",Rounding to the nearest tens.,A,A
26,2,1842,irst,219,"4th ed., 1998, p. 359.",NaN,A,A
27,2,1843,irst,320,"Temin, Peter. Iron and Steel in the 19th Centu...",Rounding to the nearest tens.,A,A
28,2,1844,irst,400,"Temin, Peter. Iron and Steel in the 19th Centu...",Rounding to the nearest tens.,A,A
29,2,1845,irst,490,"Temin, Peter. Iron and Steel in the 19th Centu...",Rounding to the nearest tens.,A,A
...,...,...,...,...,...,...,...,...
15141,990,1983,irst,0,See note.,No known production capability.,B,A
15142,990,1984,irst,0,See note.,No known production capability.,B,A
15143,990,1985,irst,0,See note.,No known production capability.,B,A
15144,990,1986,irst,0,See note.,No known production capability.,B,A
15145,990,1987,irst,0,See note.,No known production capability.,B,A
15146,990,1988,irst,0,See note.,No known production capability.,B,A
15147,990,1989,irst,0,See note.,No known production capability.,B,A
15148,990,1990,irst,0,See note.,No known production capability.,B,A
15149,990,1991,irst,0,See note.,No known production capability.,B,A
15150,990,1992,irst,0,See note.,No known production capability.,B,A
15151,990,1993,irst,0,See note.,No known production capability.,B,A
15152,990,1994,irst,0,See note.,No known production capability.,B,A
15153,990,1995,irst,0,See note.,No known production capability.,B,A
15154,990,1996,irst,0,See note.,No known production capability.,B,A
15155,990,1997,irst,0,See note.,No known production capability.,B,A
15156,990,1998,irst,0,See note.,No known production capability.,B,A
15157,990,1999,irst,0,See note.,No known production capability.,B,A
15158,990,2000,irst,0,See note.,No known production capability.,B,A
15159,990,2001,irst,0,See note.,No known production capability.,B,A
15160,990,2002,irst,0,See note.,No known production capability.,B,A
15161,990,2003,irst,0,See note.,No known production capability.,B,A
15162,990,2004,irst,0,See note.,No known production capability.,B,A
15163,990,2005,irst,0,See note.,No known production capability.,B,A
15164,990,2006,irst,0,See note.,No known production capability.,B,A
15165,990,2007,irst,0,See note.,No known production capability.,B,A
15166,990,2008,irst,0,See note.,No known production capability.,B,A
15167,990,2009,irst,0,See note.,No known production capability.,B,A
15168,990,2010,irst,0,See note.,No known production capability.,B,A
15169,990,2011,irst,0,See note.,No known production capability.,B,A
15170,990,2012,irst,0,See note.,No known production capability.,B,A

In [14]:
dfResPec.rename(columns={'ccode':'StateID', 'year':'Year', 'pec':'Amount', 'pecsource':'Source', 'pecnote':'Note', 'pecqualitycode':'QualityCode', 'pecanomalycode':'AnomalyCode'}, inplace=True)
dfResPec = dfResPec[['StateID', 'Year', 'ResourceID', 'Amount', 'Source', 'Note', 'QualityCode', 'AnomalyCode']]
dfResPec

/usr/local/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

,StateID,Year,ResourceID,Amount,Source,Note,QualityCode,AnomalyCode
0,2,1816,pec,254,"B.R. Mitchel, International Historical Statist...","Derived from production, export, and import va...",A,A
1,2,1817,pec,277,"B.R. Mitchel, International Historical Statist...","Derived from production, export, and import va...",A,A
2,2,1818,pec,302,"B.R. Mitchel, International Historical Statist...","Derived from production, export, and import va...",A,A
3,2,1819,pec,293,"B.R. Mitchel, International Historical Statist...","Derived from production, export, and import va...",A,A
4,2,1820,pec,303,"B.R. Mitchel, International Historical Statist...","Derived from production, export, and import va...",A,A
5,2,1821,pec,321,"B.R. Mitchel, International Historical Statist...","Derived from production, export, and import va...",A,A
6,2,1822,pec,332,"B.R. Mitchel, International Historical Statist...","Derived from production, export, and import va...",A,A
7,2,1823,pec,345,"B.R. Mitchel, International Historical Statist...","Derived from production, export, and import va...",A,A
8,2,1824,pec,390,"B.R. Mitchel, International Historical Statist...","Derived from production, export, and import va...",A,A
9,2,1825,pec,424,"B.R. Mitchel, International Historical Statist...","Derived from production, export, and import va...",A,A
10,2,1826,pec,502,"B.R. Mitchel, International Historical Statist...","Derived from production, export, and import va...",A,A
11,2,1827,pec,556,"B.R. Mitchel, International Historical Statist...","Derived from production, export, and import va...",A,A
12,2,1828,pec,609,"B.R. Mitchel, International Historical Statist...","Derived from production, export, and import va...",A,A
13,2,1829,pec,686,"B.R. Mitchel, International Historical Statist...","Derived from production, export, and import va...",A,A
14,2,1830,pec,799,"B.R. Mitchel, International Historical Statist...","Derived from production, export, and import va...",A,A
15,2,1831,pec,864,"B.R. Mitchel, International Historical Statist...","Derived from production, export, and import va...",A,A
16,2,1832,pec,1154,"B.R. Mitchel, International Historical Statist...","Derived from production, export, and import va...",A,A
17,2,1833,pec,1348,"B.R. Mitchel, International Historical Statist...","Derived from production, export, and import va...",A,A
18,2,1834,pec,1291,"B.R. Mitchel, International Historical Statist...","Derived from production, export, and import va...",A,A
19,2,1835,pec,1650,"B.R. Mitchel, International Historical Statist...","Derived from production, export, and import va...",A,A
20,2,1836,pec,1807,"B.R. Mitchel, International Historical Statist...","Derived from production, export, and import va...",A,A
21,2,1837,pec,2027,"B.R. Mitchel, International Historical Statist...","Derived from production, export, and import va...",A,A
22,2,1838,pec,1922,"B.R. Mitchel, International Historical Statist...","Derived from production, export, and import va...",A,A
23,2,1839,pec,2159,"B.R. Mitchel, International Historical Statist...","Derived from production, export, and import va...",A,A
24,2,1840,pec,2244,"B.R. Mitchel, International Historical Statist...","Derived from production, export, and import va...",A,A
25,2,1841,pec,2374,"B.R. Mitchel, International Historical Statist...","Derived from production, export, and import va...",A,A
26,2,1842,pec,2643,"B.R. Mitchel, International Historical Statist...","Derived from production, export, and import va...",A,A
27,2,1843,pec,2967,"B.R. Mitchel, International Historical Statist...","Derived from production, export, and import va...",A,A
28,2,1844,pec,3557,"B.R. Mitchel, International Historical Statist...","Derived from production, export, and import va...",A,A
29,2,1845,pec,4284,"B.R. Mitchel, International Historical Statist...","Derived from production, export, and import va...",A,A
...,...,...,...,...,...,...,...,...
15141,990,1983,pec,29,"UN Energy Statistics Database, 2015 Electronic...",Gross Production and Imports only. Other compo...,Z,Assumed component zero values used in PEC comp...
15142,990,1984,pec,30,"UN Energy Statistics Database, 2015 Electronic...",Gross Production and Imports only. Other compo...,Z,Assumed component zero values used in PEC comp...
15143,990,1985,pec,29,"UN Energy Statistics Database, 2015 Electronic...",Gross Production and Imports only. Other compo...,Z,Assumed component zero values used in PEC comp...
15144,990,1986,pec,29,"UN Energy Statistics Database, 2015 Electronic...",Gross Production and Imports only. Other compo...,Z,Assumed component zero values used in PEC comp...
15145,990,1987,pec,29,"UN Energy Statistics Database, 2015 Electronic...",Gross Production only. Other component(s) assu...,Z,Assumed component zero values used in PEC comp...
15146,990,1988,pec,29,"UN Energy Statistics Database, 2015 Electronic...",Gross Production and Imports only. Other compo...,Z,Assumed component zero values used in PEC comp...
15147,990,1989,pec,30,"UN Energy Statistics Database, 2015 Electronic...",Gross Production and Imports only. Other compo...,Z,Assumed component zero values used in PEC comp...
15148,990,1990,pec,30,"UN Energy Statistics Database, 2015 Electronic...",Gross Production and Imports only. Other compo...,Z,Assumed component zero values used in PEC comp...
15149,990,1991,pec,30,"UN Energy Statistics Database, 2015 Electronic...",Gross Production and Imports only. Other compo...,Z,Assumed component zero values used in PEC comp...
15150,990,1992,pec,31,"UN Energy Statistics Database, 2015 Electronic...",Gross Production and Imports only. Other compo...,Z,Assumed component zero values used in PEC comp...
15151,990,1993,pec,31,"UN Energy Statistics Database, 2015 Electronic...",Gross Production and Imports only. Other compo...,Z,Assumed component zero values used in PEC comp...
15152,990,1994,pec,32,"UN Energy Statistics Database, 2015 Electronic...",Gross Production and Imports only. Other compo...,Z,Assumed component zero values used in PEC comp...
15153,990,1995,pec,32,"UN Energy Statistics Database, 2015 Electronic...",Gross Production and Imports only. Other compo...,Z,Assumed component zero values used in PEC comp...
15154,990,1996,pec,33,"UN Energy Statistics Database, 2015 Electronic...",Gross Production and Imports only. Other compo...,Z,Assumed component zero values used in PEC comp...
15155,990,1997,pec,34,"UN Energy Statistics Database, 2015 Electronic...",Gross Production and Imports only. Other compo...,Z,Assumed component zero values used in PEC comp...
15156,990,1998,pec,34,"UN Energy Statistics Database, 2015 Electronic...",Gross Production and Imports only. Other compo...,Z,Assumed component zero values used in PEC comp...
15157,990,1999,pec,34,"UN Energy Statistics Database, 2015 Electronic...",Gross Production and Imports only. Other compo...,Z,Assumed component zero values used in PEC comp...
15158,990,2000,pec,35,"UN Energy Statistics Database, 2015 Electronic...",Gross Production and Imports only. Other compo...,Z,Assumed component zero values used in PEC comp...
15159,990,2001,pec,37,"UN Energy Statistics Database, 2015 Electronic...",Gross Production and Imports only. Other compo...,Z,Assumed component zero values used in PEC comp...
15160,990,2002,pec,39,"UN Energy Statistics Database, 2015 Electronic...",Gross Production and Imports only. Other compo...,Z,Assumed component zero values used in PEC comp...
15161,990,2003,pec,38,"UN Energy Statistics Database, 2015 Electronic...",Gross Production and Imports only. Other compo...,Z,Assumed component zero values used in PEC comp...
15162,990,2004,pec,37,"UN Energy Statistics Database, 2015 Electronic...",Gross Production and Imports only. Other compo...,Z,Assumed component zero values used in PEC comp...
15163,990,2005,pec,37,"UN Energy Statistics Database, 2015 Electronic...",Gross Production and Imports only. Other compo...,Z,Assumed component zero values used in PEC comp...
15164,990,2006,pec,38,"UN Energy Statistics Database, 2015 Electronic...",Gross Production and Imports only. Other compo...,Z,Assumed component zero values used in PEC comp...
15165,990,2007,pec,40,"UN Energy Statistics Database, 2015 Electronic...",Gross Production and Imports only. Other compo...,Z,Assumed component zero values used in PEC comp...
15166,990,2008,pec,39,"UN Energy Statistics Database, 2015 Electronic...",Gross Production and Imports only. Other compo...,Z,Assumed component zero values used in PEC comp...
15167,990,2009,pec,38,"UN Energy Statistics Database, 2015 Electronic...",Gross Production and Imports only. Other compo...,Z,Assumed component zero values used in PEC comp...
15168,990,2010,pec,38,"UN Energy Statistics Database, 2015 Electronic...",Gross Production and Imports only. Other compo...,Z,Assumed component zero values used in PEC comp...
15169,990,2011,pec,38,"UN Energy Statistics Database, 2015 Electronic...",Gross Production and Imports only. Other compo...,Z,Assumed component zero values used in PEC comp...
15170,990,2012,pec,38,"UN Energy Statistics Database, 2015 Electronic...",Gross Production and Imports only. Other compo...,Z,Assumed component zero values used in PEC comp...

In [15]:
dfResTpop.rename(columns={'ccode':'StateID', 'year':'Year', 'tpop':'Amount', 'tpopsource':'Source', 'tpopnote':'Note', 'tpopqualitycode':'QualityCode', 'tpopanomalycode':'AnomalyCode'}, inplace=True)
dfResTpop = dfResTpop[['StateID', 'Year', 'ResourceID', 'Amount', 'Source', 'Note', 'QualityCode', 'AnomalyCode']]
dfResTpop

/usr/local/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

,StateID,Year,ResourceID,Amount,Source,Note,QualityCode,AnomalyCode
0,2,1816,tpop,8659.0,Historical Statistics of the United States: C...,NaN,A,A
1,2,1817,tpop,8899.0,Historical Statistics of the United States: C...,NaN,A,A
2,2,1818,tpop,9139.0,Historical Statistics of the United States: C...,NaN,A,A
3,2,1819,tpop,9379.0,Historical Statistics of the United States: C...,NaN,A,A
4,2,1820,tpop,9618.0,Historical Statistics of the United States: C...,NaN,A,A
5,2,1821,tpop,9939.0,Historical Statistics of the United States: C...,NaN,A,A
6,2,1822,tpop,10268.0,Historical Statistics of the United States: C...,NaN,A,A
7,2,1823,tpop,10596.0,Historical Statistics of the United States: C...,NaN,A,A
8,2,1824,tpop,10924.0,Historical Statistics of the United States: C...,NaN,A,A
9,2,1825,tpop,11252.0,Historical Statistics of the United States: C...,NaN,A,A
10,2,1826,tpop,11580.0,Historical Statistics of the United States: C...,NaN,A,A
11,2,1827,tpop,11909.0,Historical Statistics of the United States: C...,NaN,A,A
12,2,1828,tpop,12237.0,Historical Statistics of the United States: C...,NaN,A,A
13,2,1829,tpop,12565.0,Historical Statistics of the United States: C...,NaN,A,A
14,2,1830,tpop,12901.0,Historical Statistics of the United States: C...,NaN,A,A
15,2,1831,tpop,13321.0,Historical Statistics of the United States: C...,NaN,A,A
16,2,1832,tpop,13742.0,Historical Statistics of the United States: C...,NaN,A,A
17,2,1833,tpop,14162.0,Historical Statistics of the United States: C...,NaN,A,A
18,2,1834,tpop,14582.0,Historical Statistics of the United States: C...,NaN,A,A
19,2,1835,tpop,15003.0,Historical Statistics of the United States: C...,NaN,A,A
20,2,1836,tpop,15423.0,Historical Statistics of the United States: C...,NaN,A,A
21,2,1837,tpop,15843.0,Historical Statistics of the United States: C...,NaN,A,A
22,2,1838,tpop,16264.0,Historical Statistics of the United States: C...,NaN,A,A
23,2,1839,tpop,16684.0,Historical Statistics of the United States: C...,NaN,A,A
24,2,1840,tpop,17120.0,Historical Statistics of the United States: C...,NaN,A,A
25,2,1841,tpop,17733.0,Historical Statistics of the United States: C...,NaN,A,A
26,2,1842,tpop,18345.0,Historical Statistics of the United States: C...,NaN,A,A
27,2,1843,tpop,18957.0,Historical Statistics of the United States: C...,NaN,A,A
28,2,1844,tpop,19569.0,Historical Statistics of the United States: C...,NaN,A,A
29,2,1845,tpop,20182.0,Historical Statistics of the United States: C...,NaN,A,A
...,...,...,...,...,...,...,...,...
15141,990,1983,tpop,156.0,"United Nations, Demographic Yearbook, Historic...",UN estimate.,A,A
15142,990,1984,tpop,157.0,"United Nations, Demographic Yearbook, Historic...",UN estimate.,A,A
15143,990,1985,tpop,157.0,"United Nations, Demographic Yearbook, Historic...",UN estimate.,A,A
15144,990,1986,tpop,157.0,"United Nations, Demographic Yearbook, Historic...",UN estimate.,A,A
15145,990,1987,tpop,158.0,"United Nations, Demographic Yearbook, Historic...",UN estimate.,A,A
15146,990,1988,tpop,162.0,"United Nations, Demographic Yearbook, Historic...",NaN,A,A
15147,990,1989,tpop,163.0,"United Nations, Demographic Yearbook, Historic...",NaN,A,A
15148,990,1990,tpop,164.0,"United Nations, Demographic Yearbook, Historic...",NaN,A,A
15149,990,1991,tpop,161.0,"United Nations, Demographic Yearbook, Historic...",UN estimate.,A,A
15150,990,1992,tpop,161.0,"United Nations, Demographic Yearbook, Historic...",NaN,A,A
15151,990,1993,tpop,162.0,"United Nations, Demographic Yearbook, Historic...",UN estimate.,A,A
15152,990,1994,tpop,164.0,"United Nations, Demographic Yearbook, Historic...",NaN,A,A
15153,990,1995,tpop,165.0,"United Nations, Demographic Yearbook, Historic...",UN estimate.,A,A
15154,990,1996,tpop,166.0,"United Nations, Demographic Yearbook, Historic...",UN estimate.,A,A
15155,990,1997,tpop,168.0,"United Nations, Demographic Yearbook, Historic...",UN estimate.,A,A
15156,990,1998,tpop,174.0,"United Nations, United Nations 1998 Revision o...",NaN,A,A
15157,990,1999,tpop,177.0,"United Nations, World Population Prospects: Th...",NaN,A,A
15158,990,2000,tpop,180.0,"United Nations, World Population Prospects: Th...",NaN,A,A
15159,990,2001,tpop,180.0,See note,NaN,E,A
15160,990,2002,tpop,177.0,"UN World Urbanizaton Prospects, 2014 Revision ...",,A,A
15161,990,2003,tpop,178.0,"UN World Urbanizaton Prospects, 2014 Revision ...",,A,A
15162,990,2004,tpop,179.0,"UN World Urbanizaton Prospects, 2014 Revision ...",,A,A
15163,990,2005,tpop,180.0,"UN World Urbanizaton Prospects, 2014 Revision ...",,A,A
15164,990,2006,tpop,181.0,"UN World Urbanizaton Prospects, 2014 Revision ...",,A,A
15165,990,2007,tpop,182.0,"UN World Urbanizaton Prospects, 2014 Revision ...",,A,A
15166,990,2008,tpop,183.0,"UN World Urbanizaton Prospects, 2014 Revision ...",,A,A
15167,990,2009,tpop,185.0,"UN World Urbanizaton Prospects, 2014 Revision ...",,A,A
15168,990,2010,tpop,186.0,"UN World Urbanizaton Prospects, 2014 Revision ...",,A,A
15169,990,2011,tpop,187.0,"UN World Urbanizaton Prospects, 2014 Revision ...",,A,A
15170,990,2012,tpop,189.0,"UN World Urbanizaton Prospects, 2014 Revision ...",,A,A

In [16]:
dfResUpop.rename(columns={'ccode':'StateID', 'year':'Year', 'upop':'Amount', 'upopsource':'Source', 'upopnote':'Note', 'upopqualitycode':'QualityCode', 'upopanomalycode':'AnomalyCode'}, inplace=True)
dfResUpop = dfResUpop[['StateID', 'Year', 'ResourceID', 'Amount', 'Source', 'Note', 'QualityCode', 'AnomalyCode']]
dfResUpop

/usr/local/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

,StateID,Year,ResourceID,Amount,Source,Note,QualityCode,AnomalyCode
0,2,1816,upop,101.0,NaN,"For 1810, HS US 1975 gives 0.",NaN,NaN
1,2,1817,upop,106.0,NaN,NaN,NaN,NaN
2,2,1818,upop,112.0,NaN,NaN,NaN,NaN
3,2,1819,upop,118.0,NaN,NaN,NaN,NaN
4,2,1820,upop,124.0,HS US 1975,NaN,NaN,NaN
5,2,1821,upop,130.0,NaN,NaN,NaN,NaN
6,2,1822,upop,136.0,NaN,NaN,NaN,NaN
7,2,1823,upop,143.0,NaN,NaN,NaN,NaN
8,2,1824,upop,151.0,NaN,NaN,NaN,NaN
9,2,1825,upop,158.0,NaN,NaN,NaN,NaN
10,2,1826,upop,166.0,NaN,NaN,NaN,NaN
11,2,1827,upop,175.0,NaN,NaN,NaN,NaN
12,2,1828,upop,183.0,NaN,NaN,NaN,NaN
13,2,1829,upop,193.0,NaN,NaN,NaN,NaN
14,2,1830,upop,203.0,HS US 1975,NaN,NaN,NaN
15,2,1831,upop,222.0,NaN,NaN,NaN,NaN
16,2,1832,upop,244.0,NaN,NaN,NaN,NaN
17,2,1833,upop,268.0,NaN,NaN,NaN,NaN
18,2,1834,upop,295.0,NaN,NaN,NaN,NaN
19,2,1835,upop,324.0,NaN,NaN,NaN,NaN
20,2,1836,upop,356.0,NaN,NaN,NaN,NaN
21,2,1837,upop,391.0,NaN,NaN,NaN,NaN
22,2,1838,upop,429.0,NaN,NaN,NaN,NaN
23,2,1839,upop,471.0,NaN,NaN,NaN,NaN
24,2,1840,upop,518.0,HS US 1975,NaN,NaN,NaN
25,2,1841,upop,562.0,NaN,NaN,NaN,NaN
26,2,1842,upop,610.0,NaN,NaN,NaN,NaN
27,2,1843,upop,662.0,NaN,NaN,NaN,NaN
28,2,1844,upop,718.0,NaN,NaN,NaN,NaN
29,2,1845,upop,779.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
15141,990,1983,upop,0.0,NaN,NaN,NaN,NaN
15142,990,1984,upop,0.0,NaN,NaN,NaN,NaN
15143,990,1985,upop,0.0,NaN,NaN,NaN,NaN
15144,990,1986,upop,0.0,NaN,NaN,NaN,NaN
15145,990,1987,upop,0.0,NaN,NaN,NaN,NaN
15146,990,1988,upop,0.0,NaN,NaN,NaN,NaN
15147,990,1989,upop,0.0,NaN,NaN,NaN,NaN
15148,990,1990,upop,0.0,NaN,NaN,NaN,NaN
15149,990,1991,upop,0.0,NaN,NaN,NaN,NaN
15150,990,1992,upop,0.0,NaN,NaN,NaN,NaN
15151,990,1993,upop,0.0,NaN,NaN,NaN,NaN
15152,990,1994,upop,0.0,NaN,NaN,B,NaN
15153,990,1995,upop,0.0,NaN,NaN,B,NaN
15154,990,1996,upop,0.0,NaN,NaN,B,NaN
15155,990,1997,upop,0.0,NaN,NaN,B,NaN
15156,990,1998,upop,0.0,NaN,NaN,B,NaN
15157,990,1999,upop,0.0,NaN,NaN,B,NaN
15158,990,2000,upop,0.0,NaN,NaN,B,NaN
15159,990,2001,upop,0.0,"UN Demographic Yearbook, 2007 table 8",NaN,A,NaN
15160,990,2002,upop,0.0,"World Urbanization Prospects, 2014 revision",NaN,B,NaN
15161,990,2003,upop,0.0,"World Urbanization Prospects, 2014 revision",NaN,B,NaN
15162,990,2004,upop,0.0,"World Urbanization Prospects, 2014 revision",NaN,B,NaN
15163,990,2005,upop,0.0,"World Urbanization Prospects, 2014 revision",NaN,B,NaN
15164,990,2006,upop,0.0,"World Urbanization Prospects, 2014 revision",NaN,B,NaN
15165,990,2007,upop,0.0,"World Urbanization Prospects, 2014 revision",NaN,B,NaN
15166,990,2008,upop,0.0,"World Urbanization Prospects, 2014 revision",NaN,B,NaN
15167,990,2009,upop,0.0,"World Urbanization Prospects, 2014 revision",NaN,B,NaN
15168,990,2010,upop,0.0,"World Urbanization Prospects, 2014 revision",NaN,B,NaN
15169,990,2011,upop,0.0,"World Urbanization Prospects, 2014 revision",NaN,B,NaN
15170,990,2012,upop,0.0,"World Urbanization Prospects, 2014 revision",NaN,B,NaN

In [17]:
resources = [dfResMilex, dfResMilPer, dfResIrst, dfResPec, dfResTpop, dfResUpop, dfResUpgrowth]
dfstateresources = pd.concat(resources)
dfstateresources

,StateID,Year,ResourceID,Amount,Source,Note,QualityCode,AnomalyCode
0,2,1816,milex,3823.00,NaN,NaN,,
1,2,1817,milex,2466.00,NaN,NaN,,
2,2,1818,milex,1910.00,NaN,NaN,,
3,2,1819,milex,2301.00,NaN,NaN,,
4,2,1820,milex,1556.00,NaN,NaN,,
5,2,1821,milex,1612.00,NaN,NaN,,
6,2,1822,milex,1079.00,NaN,NaN,,
7,2,1823,milex,1170.00,NaN,NaN,,
8,2,1824,milex,1261.00,NaN,NaN,,
9,2,1825,milex,1336.00,NaN,NaN,,
10,2,1826,milex,1658.00,NaN,NaN,,
11,2,1827,milex,1663.00,NaN,NaN,,
12,2,1828,milex,1622.00,NaN,NaN,,
13,2,1829,milex,1678.00,NaN,NaN,,
14,2,1830,milex,1687.00,NaN,NaN,,
15,2,1831,milex,1835.00,NaN,NaN,,
16,2,1832,milex,1896.00,NaN,NaN,,
17,2,1833,milex,2445.00,NaN,NaN,,
18,2,1834,milex,2073.00,NaN,NaN,,
19,2,1835,milex,2001.00,NaN,NaN,,
20,2,1836,milex,2571.00,NaN,NaN,,
21,2,1837,milex,3121.00,NaN,NaN,,
22,2,1838,milex,3083.00,NaN,NaN,,
23,2,1839,milex,2012.00,NaN,NaN,,
24,2,1840,milex,2755.00,NaN,NaN,,
25,2,1841,milex,3042.00,NaN,NaN,,
26,2,1842,milex,3011.00,NaN,NaN,,
27,2,1843,milex,1364.00,NaN,NaN,,
28,2,1844,milex,2432.00,NaN,NaN,,
29,2,1845,milex,3534.00,NaN,NaN,,
...,...,...,...,...,...,...,...,...
15141,990,1983,upopgrowth,4.62,NaN,,,
15142,990,1984,upopgrowth,4.62,NaN,,,
15143,990,1985,upopgrowth,4.59,"World Urbanization Prospects 2001, pp210-1",,,
15144,990,1986,upopgrowth,4.59,NaN,,,
15145,990,1987,upopgrowth,4.59,NaN,,,
15146,990,1988,upopgrowth,4.59,NaN,,,
15147,990,1989,upopgrowth,4.59,NaN,,,
15148,990,1990,upopgrowth,4.64,"World Urbanization Prospects 2001, pp210-1",,,
15149,990,1991,upopgrowth,4.64,NaN,,,
15150,990,1992,upopgrowth,4.64,NaN,,,
15151,990,1993,upopgrowth,4.64,NaN,,,
15152,990,1994,upopgrowth,4.64,NaN,,,
15153,990,1995,upopgrowth,4.39,"World Urbanization Prospects 2001, pp210-1",,,
15154,990,1996,upopgrowth,4.39,NaN,,,
15155,990,1997,upopgrowth,4.39,NaN,,,
15156,990,1998,upopgrowth,4.39,NaN,,,
15157,990,1999,upopgrowth,4.39,NaN,,,
15158,990,2000,upopgrowth,-0.43,"World Urbanization Prospects, 2007",,,
15159,990,2001,upopgrowth,-0.43,NaN,,,
15160,990,2002,upopgrowth,NaN,NaN,,,
15161,990,2003,upopgrowth,NaN,NaN,,,
15162,990,2004,upopgrowth,NaN,NaN,,,
15163,990,2005,upopgrowth,NaN,NaN,,,
15164,990,2006,upopgrowth,NaN,NaN,,,
15165,990,2007,upopgrowth,NaN,NaN,,,
15166,990,2008,upopgrowth,NaN,NaN,,,
15167,990,2009,upopgrowth,NaN,NaN,,,
15168,990,2010,upopgrowth,NaN,NaN,,,
15169,990,2011,upopgrowth,NaN,NaN,,,
15170,990,2012,upopgrowth,NaN,NaN,,,

In [18]:
dfstateresources.AnomalyCode.unique()

array(['', 'A', 'D', 'B', nan, 'C',
       'Assumed component zero values used in PEC computation for NMC 5.0.',
       'E', 'F'], dtype=object)

In [19]:
dfstateresources['AnomalyCode'] [dfstateresources['AnomalyCode'] == 'Assumed component zero values used in PEC computation for NMC 5.0.'] = '0'
dfstateresources.AnomalyCode.unique()

/usr/local/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

array(['', 'A', 'D', 'B', nan, 'C', '0', 'E', 'F'], dtype=object)

In [20]:
dfstateresources = dfstateresources.replace(-9, '')

In [21]:
dfstateresources.to_csv('../FinalData/state_resource.csv', encoding='utf-8', index=False)