# Explore & Resolve Discrepancies in State Identifiers

Summary:

In the first part, I attempt to use CShapes as a bridge between datasets. However, I discover that this is not feasible.

In the second part, I use a dataset from the R package 'countrycode'. I fix the errors I can identify, and as a result I have my base country-year time series.

In [1]:
import pandas as pd

In [2]:
cshapes = pd.read_csv("../Data/CShapes/Raw/country_shapes.csv", na_values=[-1])
cow = pd.read_csv("../Data/CoW/Raw/states2016.csv")
cow_ts = pd.read_csv("../Data/CoW/Raw/system2016.csv", usecols=['ccode', 'year'])
polity = pd.read_csv("../Data/PolityIV/p4v2018.csv", usecols = ['ccode', 'country', 'year'])
wb = pd.read_csv("../Data/WorldBank/Raw_API/countries_list.csv")
gw_states = pd.read_csv("../Data/GW/Raw/gw_codes.dat", sep = "\t", header=None, names = ['gw_id', 'abbr', 'name', 'startdate', 'enddate'], encoding="latin-1")
gw_micro = pd.read_csv("../Data/GW/Raw/microstatessystem.dat", sep = "\t", header=None, names = ['gw_id', 'abbr', 'name', 'startdate', 'enddate'], encoding="latin-1")
ucdp = pd.read_csv("../Data/UCDP_PRIO/Wrangled/participants_gw.csv")

## CShapes

In [3]:
cshapes['cow_edate'] = pd.to_datetime(cshapes.cow_endyear*10000+cshapes.cow_endmonth*100+cshapes.cow_endday,format='%Y%m%d')
cshapes['cow_sdate'] = pd.to_datetime(cshapes.cow_startyear*10000+cshapes.cow_startmonth*100+cshapes.cow_startday,format='%Y%m%d')
cshapes['gw_edate'] = pd.to_datetime(cshapes.gw_endyear*10000+cshapes.gw_endmonth*100+cshapes.gw_endday,format='%Y%m%d')
cshapes['gw_sdate'] = pd.to_datetime(cshapes.gw_startyear*10000+cshapes.gw_startmonth*100+cshapes.gw_startday,format='%Y%m%d')

cshapes = cshapes.drop(columns=['area', 'capital_lat', 'capital_long', 'capital_name', 
                                'cow_endyear', 'cow_endmonth', 'cow_endday', 'cow_startyear', 'cow_startmonth', 'cow_startday',
                                'gw_endyear', 'gw_endmonth', 'gw_endday', 'gw_startyear', 'gw_startmonth', 'gw_startday'])
cshapes = cshapes.sort_values(by=['iso_alpha3', 'gw_sdate', 'cow_sdate'])
cshapes

,country_name,cow_code,feature_id,gw_code,iso_alpha2,iso_alpha3,iso_name,iso_num,cow_edate,cow_sdate,gw_edate,gw_sdate
132,Afghanistan,700.0,134,700.0,AF,AFG,Afghanistan,4,2016-06-30,1946-01-01,2016-06-30,1946-01-01
164,Angola,540.0,168,540.0,AO,AGO,Angola,24,2016-06-30,1975-11-11,2016-06-30,1975-11-11
81,Albania,339.0,82,339.0,AL,ALB,Albania,8,2016-06-30,1946-01-01,2016-06-30,1946-01-01
67,Andorra,232.0,68,232.0,AD,AND,Andorra,20,2016-06-30,1993-07-28,2016-06-30,1946-01-01
131,United Arab Emirates,696.0,133,696.0,AE,ARE,United Arab Emirates,784,2016-06-30,1971-12-02,2016-06-30,1971-12-02
...,...,...,...,...,...,...,...,...,...,...,...,...
231,Kosovo,347.0,236,347.0,NaN,NaN,NaN,0,2016-06-30,2008-02-20,2016-06-30,2008-02-17
194,Egypt (United Arab Republic),651.0,199,NaN,NaN,NaN,NaN,0,1961-08-31,1958-02-01,NaT,NaT
209,Mali Federation,432.0,214,NaN,NaN,NaN,NaN,0,1960-08-19,1960-06-20,NaT,NaT
192,Egypt,651.0,197,NaN,NaN,NaN,NaN,0,1967-05-31,1961-09-01,NaT,NaT
193,Syria,652.0,198,NaN,NaN,NaN,NaN,0,1967-05-31,1961-09-29,NaT,NaT

In [4]:
cshapes_iso = list(cshapes['iso_alpha3'].unique())
cshapes_cow = list(cshapes['cow_code'].unique())
cshapes_gw = list(cshapes['gw_code'].unique())

## G&W

note: source for these files are from http://ksgleditsch.com/data-4.html

In [5]:
gw = pd.concat([gw_states, gw_micro])

In [6]:
gw['startdate'] = pd.to_datetime(gw['startdate'], format = '%d:%m:%Y')
gw['enddate'] = pd.to_datetime(gw['enddate'], format = '%d:%m:%Y')
gw = gw.rename(columns={'name': 'gw_name', 'startdate': 'gw_startdate', 'enddate': 'gw_enddate'})
gw

    gw_id abbr                         gw_name gw_startdate gw_enddate
0       2  USA        United States of America   1816-01-01 2017-12-31
1      20  CAN                          Canada   1867-07-01 2017-12-31
2      31  BHM                         Bahamas   1973-07-10 2017-12-31
3      40  CUB                            Cuba   1902-05-20 2017-12-31
4      41  HAI                           Haiti   1816-01-01 1915-07-04
..    ...  ...                             ...          ...        ...
18    973  TUV                          Tuvalu   1978-10-01 2017-12-31
19    983  MSI                Marshall Islands   1986-10-21 2017-12-31
20    986  PAL                           Palau   1994-10-01 2017-12-31
21    987  FSM  Federated States of Micronesia   1986-11-03 2017-12-31
22    990  WSM             Samoa/Western Samoa   1962-01-01 2017-12-31

[239 rows x 5 columns]

In [7]:
gw.to_csv("../Data/Other/gw_codes.csv", index=False, encoding='utf-8')

In [8]:
gw = gw[gw['gw_enddate'] > pd.to_datetime('1945-12-31')]

In [9]:
gw.to_csv("../Data/Other/gw_states_post1946.csv", index=False, encoding='utf-8')

In [10]:
gw_gw = list(gw['gw_id'].unique())
gw_iso = list(gw['abbr'].unique())

## UCDP

In [11]:
ucdp_gw = list(ucdp['gw_id'].unique())

## CoW

In [12]:
cow['cow_startdate'] = pd.to_datetime(cow.styear*10000+cow.stmonth*100+cow.stday,format='%Y%m%d')
cow['cow_enddate'] = pd.to_datetime(cow.endyear*10000+cow.endmonth*100+cow.endday,format='%Y%m%d')

cow = cow.drop(columns=['styear', 'stmonth', 'stday', 'endyear', 'endmonth', 'endday', 'version'])
cow = cow.rename(columns={'stateabb': 'ISO_alpha3', 'ccode': 'cow_id', 'statenme': 'cow_name'})
cow

,ISO_alpha3,cow_id,cow_name,cow_startdate,cow_enddate
0,USA,2,United States of America,1816-01-01,2016-12-31
1,CAN,20,Canada,1920-01-10,2016-12-31
2,BHM,31,Bahamas,1973-07-10,2016-12-31
3,CUB,40,Cuba,1902-05-20,1906-09-25
4,CUB,40,Cuba,1909-01-23,2016-12-31
...,...,...,...,...,...
238,NAU,970,Nauru,1999-09-14,2016-12-31
239,MSI,983,Marshall Islands,1991-09-17,2016-12-31
240,PAL,986,Palau,1994-12-15,2016-12-31
241,FSM,987,Federated States of Micronesia,1991-09-17,2016-12-31
242,WSM,990,Samoa,1976-12-15,2016-12-31

In [13]:
cow = cow[cow['cow_enddate'] > pd.to_datetime('1945-12-31')]

In [14]:
cow.to_csv("../Data/CoW/cow_states_post1946.csv", index=False, encoding='utf-8')

In [15]:
cow_cow = list(cow['cow_id'].unique())
cow_iso = list(cow['ISO_alpha3'].unique())

## Polity

In [16]:
polity = polity[polity['year'] > 1945]

In [17]:
polity = polity.drop_duplicates(subset=['ccode'])

In [18]:
polity.to_csv("../Data/PolityIV/polity_country_list.csv", index=False)

In [19]:
pol_cow = list(polity['ccode'].unique())

## World Bank

In [20]:
wb = wb[wb['region_name']!='Aggregates']

In [21]:
wb.to_csv("../Data/WorldBank/wb_countries.csv", index=False, encoding='utf-8')

In [22]:
wb_iso = list(wb['id'].unique())

## Compare

### CShapes vs original CoW and GW

In [23]:
set(cshapes_cow) - set(cow_cow)

{nan}

In [24]:
set(cow_cow) - set(cshapes_cow)

set()

In [25]:
cshapes_not_in_gw = set(cshapes_gw) - set(gw_gw)
cshapes[cshapes['gw_code'].isin(list(cshapes_not_in_gw))]

,country_name,cow_code,feature_id,gw_code,iso_alpha2,iso_alpha3,iso_name,iso_num,cow_edate,cow_sdate,gw_edate,gw_sdate
227,USSR,365.0,232,NaN,SU,SUN,Union of Soviet Socialist Republics,810,1991-12-25,1991-09-06,NaT,NaT
225,Yugoslavia,345.0,230,NaN,YU,YUG,"Yugoslavia, Socialist Federal Republic of",890,1992-04-06,1992-01-15,NaT,NaT
228,Yugoslavia,345.0,233,NaN,YU,YUG,"Yugoslavia, Socialist Federal Republic of",890,1993-04-07,1992-04-07,NaT,NaT
194,Egypt (United Arab Republic),651.0,199,NaN,NaN,NaN,NaN,0,1961-08-31,1958-02-01,NaT,NaT
209,Mali Federation,432.0,214,NaN,NaN,NaN,NaN,0,1960-08-19,1960-06-20,NaT,NaT
192,Egypt,651.0,197,NaN,NaN,NaN,NaN,0,1967-05-31,1961-09-01,NaT,NaT
193,Syria,652.0,198,NaN,NaN,NaN,NaN,0,1967-05-31,1961-09-29,NaT,NaT

^ excepting the NaNs, these all look like microstates, and may be included in the seperate G&W microstate list

In [26]:
gw_not_in_cshapes = set(gw_gw) - set(cshapes_gw)
gw[gw['gw_id'].isin(list(gw_not_in_cshapes))]

     gw_id abbr        gw_name gw_startdate gw_enddate
183    711  TBT          Tibet   1913-01-01 1950-10-01
10     396  ABK       Abkhazia   2008-08-26 2017-12-31
11     397  SOT  South Ossetia   2008-08-26 2017-12-31

### UCDP vs GW

751 is the Government of Hyderabad. Unclear if this is actually a state or just a territory.

In [27]:
set(ucdp_gw) - set(gw_gw)

{751}

### Polity & CoW

In [28]:
pol_not_in_cow = set(pol_cow) - set(cow_cow)

In [29]:
polity[polity['ccode'].isin(list(pol_not_in_cow))]

       ccode      country  year
7730     342       Serbia  2006
7913     348   Montenegro  2006
8557     364         USSR  1946
11606    525  South Sudan  2011
11614    529     Ethiopia  1993
15934    769     Pakistan  1947
16808    818      Vietnam  1976

^ polity codes are supposed to be derived from CoW country codes, but they must have added some

- Serbia does not exist in Polity between 1921 and 2005
- Ethiopia given an unofficial code (ETI instead of ETH) in 1993

In [30]:
cow_not_in_pol = set(cow_cow) - set(pol_cow)

In [31]:
cow[cow['cow_id'].isin(list(cow_not_in_pol))]

,ISO_alpha3,cow_id,cow_name,cow_startdate,cow_enddate
2,BHM,31,Bahamas,1973-07-10,2016-12-31
11,BAR,53,Barbados,1966-11-30,2016-12-31
12,DMA,54,Dominica,1978-11-03,2016-12-31
13,GRN,55,Grenada,1974-02-07,2016-12-31
14,SLU,56,St. Lucia,1979-02-22,2016-12-31
15,SVG,57,St. Vincent and the Grenadines,1979-10-27,2016-12-31
16,AAB,58,Antigua & Barbuda,1981-11-01,2016-12-31
17,SKN,60,St. Kitts and Nevis,1983-09-19,2016-12-31
19,BLZ,80,Belize,1981-09-21,2016-12-31
49,MNC,221,Monaco,1993-05-28,2016-12-31
50,LIE,223,Liechtenstein,1990-09-18,2016-12-31
53,AND,232,Andorra,1993-07-28,2016-12-31
80,SNM,331,San Marino,1992-03-02,2016-12-31
84,MLT,338,Malta,1964-09-21,2016-12-31
119,ICE,395,Iceland,1944-06-17,2016-12-31
121,STP,403,Sao Tome and Principe,1975-07-12,2016-12-31
147,ZAN,511,Zanzibar,1963-12-19,1964-04-26
168,SEY,591,Seychelles,1976-06-29,2016-12-31
216,MAD,781,Maldives,1965-07-26,2016-12-31
225,BRU,835,Brunei,1984-01-01,2016-12-31
232,VAN,935,Vanuatu,1981-09-15,2016-12-31
234,KIR,946,Kiribati,1999-09-14,2016-12-31
235,TUV,947,Tuvalu,2000-09-05,2016-12-31
237,TON,955,Tonga,1999-09-14,2016-12-31
238,NAU,970,Nauru,1999-09-14,2016-12-31
239,MSI,983,Marshall Islands,1991-09-17,2016-12-31
240,PAL,986,Palau,1994-12-15,2016-12-31
241,FSM,987,Federated States of Micronesia,1991-09-17,2016-12-31
242,WSM,990,Samoa,1976-12-15,2016-12-31

^ again, these all look like microstates, which Polity must not track

### World Bank vs CoW & GW

In [32]:
wb_not_in_cshapes = set(wb_iso) - set(cshapes_iso)
wb[wb['id'].isin(list(wb_not_in_cshapes))]

,id,iso2code,name,capitalcity,latitude,longitude,region_name,adminregion_name,incomelevel_value,lendingtype_value
0,ABW,AW,Aruba,Oranjestad,12.516700,-70.016700,Latin America & Caribbean,NaN,High income,Not classified
11,ASM,AS,American Samoa,Pago Pago,-14.284600,-170.691000,East Asia & Pacific,East Asia & Pacific (excluding high income),Upper middle income,Not classified
32,BMU,BM,Bermuda,Hamilton,32.329300,-64.706000,North America,NaN,High income,Not classified
47,CHI,JG,Channel Islands,NaN,NaN,NaN,Europe & Central Asia,NaN,High income,Not classified
63,CUW,CW,Curacao,Willemstad,NaN,NaN,Latin America & Caribbean,NaN,High income,Not classified
64,CYM,KY,Cayman Islands,George Town,19.302200,-81.385700,Latin America & Caribbean,NaN,High income,Not classified
101,FRO,FO,Faroe Islands,Torshavn,61.892600,-6.911810,Europe & Central Asia,NaN,High income,Not classified
108,GIB,GI,Gibraltar,NaN,NaN,NaN,Europe & Central Asia,NaN,High income,Not classified
115,GRL,GL,Greenland,Nuuk,64.183600,-51.721400,Europe & Central Asia,NaN,High income,Not classified
117,GUM,GU,Guam,Agana,13.444300,144.794000,East Asia & Pacific,NaN,High income,Not classified
120,HKG,HK,"Hong Kong SAR, China",NaN,22.396400,114.109000,East Asia & Pacific,NaN,High income,Not classified
133,IMN,IM,Isle of Man,Douglas,54.150900,-4.479280,Europe & Central Asia,NaN,High income,Not classified
172,MAC,MO,"Macao SAR, China",NaN,22.166700,113.550000,East Asia & Pacific,NaN,High income,Not classified
173,MAF,MF,St. Martin (French part),Marigot,NaN,NaN,Latin America & Caribbean,NaN,High income,Not classified
192,MNP,MP,Northern Mariana Islands,Saipan,15.193500,145.765000,East Asia & Pacific,NaN,High income,Not classified
201,NCL,NC,New Caledonia,Noum'ea,-22.267700,166.464000,East Asia & Pacific,NaN,High income,Not classified
224,PRI,PR,Puerto Rico,San Juan,18.230000,-66.000000,Latin America & Caribbean,NaN,High income,Not classified
228,PSE,PS,West Bank and Gaza,NaN,NaN,NaN,Middle East & North Africa,Middle East & North Africa (excluding high inc...,Lower middle income,Not classified
231,PYF,PF,French Polynesia,Papeete,-17.535000,-149.570000,East Asia & Pacific,NaN,High income,Not classified
260,SXM,SX,Sint Maarten (Dutch part),Philipsburg,NaN,NaN,Latin America & Caribbean,NaN,High income,Not classified
264,TCA,TC,Turks and Caicos Islands,Grand Turk,21.460278,-71.141389,Latin America & Caribbean,NaN,High income,Not classified
292,VGB,VG,British Virgin Islands,Road Town,18.431389,-64.623056,Latin America & Caribbean,NaN,High income,Not classified
293,VIR,VI,Virgin Islands (U.S.),Charlotte Amalie,18.335800,-64.896300,Latin America & Caribbean,NaN,High income,Not classified
298,XKX,XK,Kosovo,Pristina,42.565000,20.926000,Europe & Central Asia,Europe & Central Asia (excluding high income),Upper middle income,IDA

In [33]:
cshapes_not_in_wb = set(cshapes_iso) - set(wb_iso)
cshapes[cshapes['iso_alpha3'].isin(list(cshapes_not_in_wb))]

,country_name,cow_code,feature_id,gw_code,iso_alpha2,iso_alpha3,iso_name,iso_num,cow_edate,cow_sdate,gw_edate,gw_sdate
186,Czechoslovakia,315.0,190,315.0,CS,CSK,Czechoslovakia,200,1992-12-31,1946-01-01,1992-12-31,1946-01-01
185,Germany Democratic Republic,265.0,189,265.0,DD,DDR,German Democratic Republic,278,1990-10-02,1954-03-25,1990-10-02,1949-10-05
226,Serbia and Montenegro,345.0,231,345.0,CS,SCG,Serbia and Montenegro,891,2006-06-11,1993-04-08,2006-06-02,1992-04-27
188,USSR,365.0,192,365.0,SU,SUN,Union of Soviet Socialist Republics,810,1991-09-05,1946-01-01,1991-08-24,1946-01-01
247,USSR,NaN,249,365.0,SU,SUN,Union of Soviet Socialist Republics,810,NaT,NaT,1991-08-26,1991-08-25
248,USSR,NaN,250,365.0,SU,SUN,Union of Soviet Socialist Republics,810,NaT,NaT,1991-08-30,1991-08-27
249,USSR,NaN,251,365.0,SU,SUN,Union of Soviet Socialist Republics,810,NaT,NaT,1991-09-05,1991-08-31
250,USSR,NaN,252,365.0,SU,SUN,Union of Soviet Socialist Republics,810,NaT,NaT,1991-09-08,1991-09-06
251,USSR,NaN,253,365.0,SU,SUN,Union of Soviet Socialist Republics,810,NaT,NaT,1991-10-26,1991-09-09
252,USSR,NaN,254,365.0,SU,SUN,Union of Soviet Socialist Republics,810,NaT,NaT,1991-11-30,1991-10-27
253,USSR,NaN,255,365.0,SU,SUN,Union of Soviet Socialist Republics,810,NaT,NaT,1991-12-15,1991-12-01
254,USSR,NaN,256,365.0,SU,SUN,Union of Soviet Socialist Republics,810,NaT,NaT,1991-12-20,1991-12-16
227,USSR,365.0,232,NaN,SU,SUN,Union of Soviet Socialist Republics,810,1991-12-25,1991-09-06,NaT,NaT
201,Vietnam,816.0,206,816.0,VD,VDR,Democratic Republic of Viet-Nam,704,1975-04-30,1954-07-21,1975-04-30,1954-05-01
196,Yemen People's Republic,680.0,201,680.0,YD,YMD,Democratic Yemen,720,1990-05-21,1967-11-30,1990-05-21,1967-11-30
187,Yugoslavia,345.0,191,345.0,YU,YUG,"Yugoslavia, Socialist Federal Republic of",890,1992-01-14,1946-01-01,1991-11-19,1946-01-01
246,Yugoslavia,NaN,247,345.0,YU,YUG,"Yugoslavia, Socialist Federal Republic of",890,NaT,NaT,1992-04-26,1991-11-20
225,Yugoslavia,345.0,230,NaN,YU,YUG,"Yugoslavia, Socialist Federal Republic of",890,1992-04-06,1992-01-15,NaT,NaT
228,Yugoslavia,345.0,233,NaN,YU,YUG,"Yugoslavia, Socialist Federal Republic of",890,1993-04-07,1992-04-07,NaT,NaT
14,Canada,20.0,14,20.0,NaN,NaN,NaN,0,1948-06-30,1946-01-01,1948-06-30,1946-01-01
90,Egypt,651.0,92,651.0,NaN,NaN,NaN,0,1958-01-31,1946-01-01,1967-05-31,1946-01-01
140,China,710.0,142,710.0,NaN,NaN,NaN,0,1949-12-07,1946-01-01,1949-12-07,1946-01-01
240,Brazil,140.0,241,140.0,NaN,NaN,NaN,0,1960-04-20,1946-01-01,1960-04-20,1946-01-01
94,Syria,652.0,96,652.0,NaN,NaN,NaN,0,1958-02-01,1946-04-17,1967-05-31,1946-01-01
174,Indonesia,850.0,178,850.0,NaN,NaN,NaN,0,1963-04-30,1949-12-27,1963-04-30,1946-01-01
223,Pakistan,770.0,228,770.0,NaN,NaN,NaN,0,1948-12-31,1947-08-14,1948-12-31,1947-08-14
224,India,750.0,229,750.0,NaN,NaN,NaN,0,1948-12-31,1947-08-15,1948-12-31,1947-08-15
60,Israel,666.0,61,666.0,NaN,NaN,NaN,0,1967-05-31,1948-05-14,1967-05-31,1948-05-14
199,Pakistan,770.0,204,770.0,NaN,NaN,NaN,0,1971-12-15,1949-01-01,1971-12-15,1949-01-01
70,Libya,620.0,71,620.0,NaN,NaN,NaN,0,1972-12-31,1951-12-24,1972-12-31,1951-12-24
43,Morocco,600.0,43,600.0,NaN,NaN,NaN,0,1958-03-31,1956-03-02,1958-03-31,1956-03-02
203,Malaysia,820.0,208,820.0,NaN,NaN,NaN,0,1963-09-30,1957-08-31,1963-09-30,1957-08-31
210,Cameroon,471.0,215,471.0,NaN,NaN,NaN,0,1961-09-30,1960-01-01,1961-09-30,1960-01-01
74,Chad,483.0,75,483.0,NaN,NaN,NaN,0,1972-12-31,1960-08-11,1972-12-31,1960-08-11
211,Nigeria,475.0,216,475.0,NaN,NaN,NaN,0,1961-05-31,1960-10-01,1961-05-31,1960-10-01
237,Tanzania,510.0,193,510.0,NaN,NaN,NaN,0,1964-03-31,1961-12-09,1964-03-31,1961-12-09
202,Malaysia,820.0,207,820.0,NaN,NaN,NaN,0,1965-07-31,1963-10-01,1965-07-31,1963-10-01
189,Zanzibar,511.0,194,511.0,NaN,NaN,NaN,0,1964-04-26,1963-12-19,1964-04-26,1963-12-19
231,Kosovo,347.0,236,347.0,NaN,NaN,NaN,0,2016-06-30,2008-02-20,2016-06-30,2008-02-17
194,Egypt (United Arab Republic),651.0,199,NaN,NaN,NaN,NaN,0,1961-08-31,1958-02-01,NaT,NaT
209,Mali Federation,432.0,214,NaN,NaN,NaN,NaN,0,1960-08-19,1960-06-20,NaT,NaT
192,Egypt,651.0,197,NaN,NaN,NaN,NaN,0,1967-05-31,1961-09-01,NaT,NaT
193,Syria,652.0,198,NaN,NaN,NaN,NaN,0,1967-05-31,1961-09-29,NaT,NaT

## Conclusion

This is not a solvable problem with the datasets that I have. Instead, I will use the R package "countrycode". See the github repo here: https://github.com/vincentarelbundock/countrycode

# Part 2: Explore & resolve discrepancies using 'countrycode' package

In [34]:
pd.set_option('display.max_rows', 100)

In [35]:
cc = pd.read_csv("../Data/countrycode/country_conversion_table.csv", dtype={'cown': 'Int64', 'gwn': 'Int64', 'p4n': 'Int64'})

In [36]:
cc_cow = list(cc['cown'].unique())
cow_not_in_cc = set(cow_cow) - set(cc_cow)
cow[cow['cow_id'].isin(list(cow_not_in_cc))]

    ISO_alpha3  cow_id cow_name cow_startdate cow_enddate
221        DRV     816  Vietnam    1954-07-21  2016-12-31

In [37]:
cc_gw = list(cc['gwn'].unique())
gw_not_in_cc = set(gw_gw) - set(cc_gw)
gw[gw['gw_id'].isin(list(gw_not_in_cc))]

     gw_id abbr                          gw_name gw_startdate gw_enddate
183    711  TBT                            Tibet   1913-01-01 1950-10-01
203    816  DRV  Vietnam, Democratic Republic of   1954-05-01 2017-12-31
10     396  ABK                         Abkhazia   2008-08-26 2017-12-31
11     397  SOT                    South Ossetia   2008-08-26 2017-12-31
12     403  STP            SÃ£o TomÃ© and Principe   1975-07-12 2017-12-31

In [38]:
cc_p4 = list(cc['p4n'].unique())
pol_not_in_cc = set(pol_cow) - set(cc_p4)
polity[polity['ccode'].isin(list(pol_not_in_cc))]

       ccode      country  year
7913     348   Montenegro  2006
8557     364         USSR  1946
11606    525  South Sudan  2011
11614    529     Ethiopia  1993
15934    769     Pakistan  1947
16808    818      Vietnam  1976

In [39]:
cc_wb = list(cc['wb'].unique())
wb_not_in_cc = set(wb_iso) - set(cc_wb)
wb[wb['id'].isin(list(wb_not_in_cc))]

,id,iso2code,name,capitalcity,latitude,longitude,region_name,adminregion_name,incomelevel_value,lendingtype_value
0,ABW,AW,Aruba,Oranjestad,12.516700,-70.016700,Latin America & Caribbean,NaN,High income,Not classified
11,ASM,AS,American Samoa,Pago Pago,-14.284600,-170.691000,East Asia & Pacific,East Asia & Pacific (excluding high income),Upper middle income,Not classified
32,BMU,BM,Bermuda,Hamilton,32.329300,-64.706000,North America,NaN,High income,Not classified
47,CHI,JG,Channel Islands,NaN,NaN,NaN,Europe & Central Asia,NaN,High income,Not classified
63,CUW,CW,Curacao,Willemstad,NaN,NaN,Latin America & Caribbean,NaN,High income,Not classified
64,CYM,KY,Cayman Islands,George Town,19.302200,-81.385700,Latin America & Caribbean,NaN,High income,Not classified
101,FRO,FO,Faroe Islands,Torshavn,61.892600,-6.911810,Europe & Central Asia,NaN,High income,Not classified
108,GIB,GI,Gibraltar,NaN,NaN,NaN,Europe & Central Asia,NaN,High income,Not classified
115,GRL,GL,Greenland,Nuuk,64.183600,-51.721400,Europe & Central Asia,NaN,High income,Not classified
117,GUM,GU,Guam,Agana,13.444300,144.794000,East Asia & Pacific,NaN,High income,Not classified
120,HKG,HK,"Hong Kong SAR, China",NaN,22.396400,114.109000,East Asia & Pacific,NaN,High income,Not classified
133,IMN,IM,Isle of Man,Douglas,54.150900,-4.479280,Europe & Central Asia,NaN,High income,Not classified
172,MAC,MO,"Macao SAR, China",NaN,22.166700,113.550000,East Asia & Pacific,NaN,High income,Not classified
173,MAF,MF,St. Martin (French part),Marigot,NaN,NaN,Latin America & Caribbean,NaN,High income,Not classified
192,MNP,MP,Northern Mariana Islands,Saipan,15.193500,145.765000,East Asia & Pacific,NaN,High income,Not classified
201,NCL,NC,New Caledonia,Noum'ea,-22.267700,166.464000,East Asia & Pacific,NaN,High income,Not classified
224,PRI,PR,Puerto Rico,San Juan,18.230000,-66.000000,Latin America & Caribbean,NaN,High income,Not classified
228,PSE,PS,West Bank and Gaza,NaN,NaN,NaN,Middle East & North Africa,Middle East & North Africa (excluding high inc...,Lower middle income,Not classified
231,PYF,PF,French Polynesia,Papeete,-17.535000,-149.570000,East Asia & Pacific,NaN,High income,Not classified
248,SOM,SO,Somalia,Mogadishu,2.075150,45.325400,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Low income,IDA
260,SXM,SX,Sint Maarten (Dutch part),Philipsburg,NaN,NaN,Latin America & Caribbean,NaN,High income,Not classified
264,TCA,TC,Turks and Caicos Islands,Grand Turk,21.460278,-71.141389,Latin America & Caribbean,NaN,High income,Not classified
292,VGB,VG,British Virgin Islands,Road Town,18.431389,-64.623056,Latin America & Caribbean,NaN,High income,Not classified
293,VIR,VI,Virgin Islands (U.S.),Charlotte Amalie,18.335800,-64.896300,Latin America & Caribbean,NaN,High income,Not classified

## Things to Fix

- Vietnam
    - fill NA values for 'cown' with 816 
    - correct gwn by replacing 817 with 816 for Vietnam after 1976
    - fill single NA value for 'p4n' with 816 (in 1954)
    - change p4n for Vietnam after 1976 to 818
- Russia
    - change p4n for years before 1992 to 364
- Pakistan
    - change p4n for years before 1972 to 769
- Ethiopia
    - change p4n for years after 1993 to 529
- South Sudan
    - change p4n to 525 (626 is wrong)
    - 626 refers to North Sudan so...
- North Sudan
    - change p4n for Sudan (SDN) after 2010 to 626
- Somalia
    - give wb id of SOM
    - remove years before 1960
- Montenegro
    - drop rows with year < 2006
    - change p4n to 348 (341 is wrong)
    - 341 refers to Kosovo so...
- Kosovo
    - drop rows with year < 2008
    - change p4n to 341 (347 is wrong)
    - add iso code XKX
    - continent = Europe, region = Southern Europe
    - 347 refers to Yugoslavia so...
- Yugoslavia
    - change p4n to 347 after 1990
    - delete rows after 2006, Yugoslavia becomes Serbia
    - add wb id SRB
    - continent = Europe, region = Southern Europe
- Serbia
    - delete rows before 2006 (was Yugoslavia)
    - add CoW code 345

In [40]:
mask_vietnam = cc['iso3c']=="VNM"

cc.loc[mask_vietnam, 'cown'] = cc.loc[mask_vietnam, 'cown'].fillna(816)
cc.loc[mask_vietnam, 'gwn'] = cc.loc[mask_vietnam, 'cown']
cc.loc[mask_vietnam, 'p4n'] = cc.loc[mask_vietnam, 'p4n'].fillna(816)

mask_vietnamnew = (cc['cown']==816) & (cc['year'] >= 1976)

cc.loc[mask_vietnamnew, 'p4n'] = 818

cc[mask_vietnam]

,country.name.en,year,continent,region,cown,gwn,iso3c,p4n,wb
12072,Vietnam,1955,Asia,South-Eastern Asia,817,817,VNM,817,VNM
12073,Vietnam,1956,Asia,South-Eastern Asia,817,817,VNM,817,VNM
12074,Vietnam,1957,Asia,South-Eastern Asia,817,817,VNM,817,VNM
12075,Vietnam,1958,Asia,South-Eastern Asia,817,817,VNM,817,VNM
12076,Vietnam,1959,Asia,South-Eastern Asia,817,817,VNM,817,VNM
12077,Vietnam,1960,Asia,South-Eastern Asia,817,817,VNM,817,VNM
12078,Vietnam,1961,Asia,South-Eastern Asia,817,817,VNM,817,VNM
12079,Vietnam,1962,Asia,South-Eastern Asia,817,817,VNM,817,VNM
12080,Vietnam,1963,Asia,South-Eastern Asia,817,817,VNM,817,VNM
12081,Vietnam,1964,Asia,South-Eastern Asia,817,817,VNM,817,VNM
12082,Vietnam,1965,Asia,South-Eastern Asia,817,817,VNM,817,VNM
12083,Vietnam,1966,Asia,South-Eastern Asia,817,817,VNM,817,VNM
12084,Vietnam,1967,Asia,South-Eastern Asia,817,817,VNM,817,VNM
12085,Vietnam,1968,Asia,South-Eastern Asia,817,817,VNM,817,VNM
12086,Vietnam,1969,Asia,South-Eastern Asia,817,817,VNM,817,VNM
12087,Vietnam,1970,Asia,South-Eastern Asia,817,817,VNM,817,VNM
12088,Vietnam,1971,Asia,South-Eastern Asia,817,817,VNM,817,VNM
12089,Vietnam,1972,Asia,South-Eastern Asia,817,817,VNM,817,VNM
12090,Vietnam,1973,Asia,South-Eastern Asia,817,817,VNM,817,VNM
12091,Vietnam,1974,Asia,South-Eastern Asia,817,817,VNM,817,VNM
12092,Vietnam,1975,Asia,South-Eastern Asia,817,817,VNM,817,VNM
12093,Vietnam,1954,Asia,South-Eastern Asia,817,817,VNM,816,VNM
12094,Vietnam,2018,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12095,Vietnam,2010,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12096,Vietnam,2011,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12097,Vietnam,2016,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12098,Vietnam,2017,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12099,Vietnam,1978,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12100,Vietnam,1979,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12101,Vietnam,1980,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12102,Vietnam,1981,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12103,Vietnam,1982,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12104,Vietnam,1983,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12105,Vietnam,1976,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12106,Vietnam,1977,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12107,Vietnam,1984,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12108,Vietnam,1985,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12109,Vietnam,1986,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12110,Vietnam,1987,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12111,Vietnam,1988,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12112,Vietnam,1989,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12113,Vietnam,1990,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12114,Vietnam,1991,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12115,Vietnam,1992,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12116,Vietnam,1993,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12117,Vietnam,2003,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12118,Vietnam,2004,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12119,Vietnam,2005,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12120,Vietnam,2006,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12121,Vietnam,2007,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12122,Vietnam,2008,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12123,Vietnam,2009,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12124,Vietnam,2012,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12125,Vietnam,2013,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12126,Vietnam,2014,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12127,Vietnam,2015,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12128,Vietnam,2002,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12129,Vietnam,1994,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12130,Vietnam,1995,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12131,Vietnam,2001,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12132,Vietnam,1996,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12133,Vietnam,1998,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12134,Vietnam,1999,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12135,Vietnam,2000,Asia,South-Eastern Asia,816,816,VNM,818,VNM
12136,Vietnam,1997,Asia,South-Eastern Asia,816,816,VNM,818,VNM

In [41]:
mask_russia = cc['iso3c']=="RUS"
mask_ussr = (cc['iso3c']=="RUS") & (cc['year'] < 1992)
cc.loc[mask_ussr, 'p4n'] = 364
cc[mask_russia]

,country.name.en,year,continent,region,cown,gwn,iso3c,p4n,wb
9072,Russia,1992,Europe,Eastern Europe,365,365,RUS,365,RUS
9073,Russia,1993,Europe,Eastern Europe,365,365,RUS,365,RUS
9074,Russia,1994,Europe,Eastern Europe,365,365,RUS,365,RUS
9075,Russia,1995,Europe,Eastern Europe,365,365,RUS,365,RUS
9076,Russia,1996,Europe,Eastern Europe,365,365,RUS,365,RUS
9077,Russia,1997,Europe,Eastern Europe,365,365,RUS,365,RUS
9078,Russia,1998,Europe,Eastern Europe,365,365,RUS,365,RUS
9079,Russia,1999,Europe,Eastern Europe,365,365,RUS,365,RUS
9080,Russia,2000,Europe,Eastern Europe,365,365,RUS,365,RUS
9081,Russia,2001,Europe,Eastern Europe,365,365,RUS,365,RUS
9082,Russia,2002,Europe,Eastern Europe,365,365,RUS,365,RUS
9083,Russia,2003,Europe,Eastern Europe,365,365,RUS,365,RUS
9084,Russia,2004,Europe,Eastern Europe,365,365,RUS,365,RUS
9085,Russia,2005,Europe,Eastern Europe,365,365,RUS,365,RUS
9086,Russia,2006,Europe,Eastern Europe,365,365,RUS,365,RUS
9087,Russia,2007,Europe,Eastern Europe,365,365,RUS,365,RUS
9088,Russia,2008,Europe,Eastern Europe,365,365,RUS,365,RUS
9089,Russia,2009,Europe,Eastern Europe,365,365,RUS,365,RUS
9090,Russia,2010,Europe,Eastern Europe,365,365,RUS,365,RUS
9091,Russia,2011,Europe,Eastern Europe,365,365,RUS,365,RUS
9092,Russia,2012,Europe,Eastern Europe,365,365,RUS,365,RUS
9093,Russia,2013,Europe,Eastern Europe,365,365,RUS,365,RUS
9094,Russia,2014,Europe,Eastern Europe,365,365,RUS,365,RUS
9095,Russia,2015,Europe,Eastern Europe,365,365,RUS,365,RUS
9096,Russia,2016,Europe,Eastern Europe,365,365,RUS,365,RUS
9097,Russia,2017,Europe,Eastern Europe,365,365,RUS,365,RUS
9098,Russia,2018,Europe,Eastern Europe,365,365,RUS,365,RUS
9099,Russia,1946,Europe,Eastern Europe,365,365,RUS,364,RUS
9100,Russia,1947,Europe,Eastern Europe,365,365,RUS,364,RUS
9101,Russia,1948,Europe,Eastern Europe,365,365,RUS,364,RUS
9102,Russia,1949,Europe,Eastern Europe,365,365,RUS,364,RUS
9103,Russia,1950,Europe,Eastern Europe,365,365,RUS,364,RUS
9104,Russia,1951,Europe,Eastern Europe,365,365,RUS,364,RUS
9105,Russia,1952,Europe,Eastern Europe,365,365,RUS,364,RUS
9106,Russia,1953,Europe,Eastern Europe,365,365,RUS,364,RUS
9107,Russia,1954,Europe,Eastern Europe,365,365,RUS,364,RUS
9108,Russia,1955,Europe,Eastern Europe,365,365,RUS,364,RUS
9109,Russia,1956,Europe,Eastern Europe,365,365,RUS,364,RUS
9110,Russia,1957,Europe,Eastern Europe,365,365,RUS,364,RUS
9111,Russia,1958,Europe,Eastern Europe,365,365,RUS,364,RUS
9112,Russia,1959,Europe,Eastern Europe,365,365,RUS,364,RUS
9113,Russia,1960,Europe,Eastern Europe,365,365,RUS,364,RUS
9114,Russia,1961,Europe,Eastern Europe,365,365,RUS,364,RUS
9115,Russia,1962,Europe,Eastern Europe,365,365,RUS,364,RUS
9116,Russia,1963,Europe,Eastern Europe,365,365,RUS,364,RUS
9117,Russia,1964,Europe,Eastern Europe,365,365,RUS,364,RUS
9118,Russia,1965,Europe,Eastern Europe,365,365,RUS,364,RUS
9119,Russia,1966,Europe,Eastern Europe,365,365,RUS,364,RUS
9120,Russia,1967,Europe,Eastern Europe,365,365,RUS,364,RUS
9121,Russia,1968,Europe,Eastern Europe,365,365,RUS,364,RUS
9122,Russia,1969,Europe,Eastern Europe,365,365,RUS,364,RUS
9123,Russia,1970,Europe,Eastern Europe,365,365,RUS,364,RUS
9124,Russia,1971,Europe,Eastern Europe,365,365,RUS,364,RUS
9125,Russia,1972,Europe,Eastern Europe,365,365,RUS,364,RUS
9126,Russia,1973,Europe,Eastern Europe,365,365,RUS,364,RUS
9127,Russia,1974,Europe,Eastern Europe,365,365,RUS,364,RUS
9128,Russia,1975,Europe,Eastern Europe,365,365,RUS,364,RUS
9129,Russia,1976,Europe,Eastern Europe,365,365,RUS,364,RUS
9130,Russia,1977,Europe,Eastern Europe,365,365,RUS,364,RUS
9131,Russia,1978,Europe,Eastern Europe,365,365,RUS,364,RUS
9132,Russia,1979,Europe,Eastern Europe,365,365,RUS,364,RUS
9133,Russia,1980,Europe,Eastern Europe,365,365,RUS,364,RUS
9134,Russia,1981,Europe,Eastern Europe,365,365,RUS,364,RUS
9135,Russia,1982,Europe,Eastern Europe,365,365,RUS,364,RUS
9136,Russia,1983,Europe,Eastern Europe,365,365,RUS,364,RUS
9137,Russia,1984,Europe,Eastern Europe,365,365,RUS,364,RUS
9138,Russia,1985,Europe,Eastern Europe,365,365,RUS,364,RUS
9139,Russia,1986,Europe,Eastern Europe,365,365,RUS,364,RUS
9140,Russia,1987,Europe,Eastern Europe,365,365,RUS,364,RUS
9141,Russia,1988,Europe,Eastern Europe,365,365,RUS,364,RUS
9142,Russia,1989,Europe,Eastern Europe,365,365,RUS,364,RUS
9143,Russia,1990,Europe,Eastern Europe,365,365,RUS,364,RUS
9144,Russia,1991,Europe,Eastern Europe,365,365,RUS,364,RUS

In [42]:
mask_pakistan = cc['iso3c']=="PAK"
mask_pakistan2 = (cc['iso3c']=="PAK") & (cc['year'] < 1972)
cc.loc[mask_pakistan2, 'p4n'] = 769
cc[mask_pakistan]

     country.name.en  year continent         region  cown  gwn iso3c  p4n   wb
8318        Pakistan  1972      Asia  Southern Asia   770  770   PAK  770  PAK
8319        Pakistan  1973      Asia  Southern Asia   770  770   PAK  770  PAK
8320        Pakistan  1974      Asia  Southern Asia   770  770   PAK  770  PAK
8321        Pakistan  1975      Asia  Southern Asia   770  770   PAK  770  PAK
8322        Pakistan  1976      Asia  Southern Asia   770  770   PAK  770  PAK
8323        Pakistan  1977      Asia  Southern Asia   770  770   PAK  770  PAK
8324        Pakistan  1978      Asia  Southern Asia   770  770   PAK  770  PAK
8325        Pakistan  1979      Asia  Southern Asia   770  770   PAK  770  PAK
8326        Pakistan  1980      Asia  Southern Asia   770  770   PAK  770  PAK
8327        Pakistan  1981      Asia  Southern Asia   770  770   PAK  770  PAK
8328        Pakistan  1982      Asia  Southern Asia   770  770   PAK  770  PAK
8329        Pakistan  1983      Asia  Southern Asia   770  770   PAK  770  PAK
8330        Pakistan  1984      Asia  Southern Asia   770  770   PAK  770  PAK
8331        Pakistan  1985      Asia  Southern Asia   770  770   PAK  770  PAK
8332        Pakistan  1986      Asia  Southern Asia   770  770   PAK  770  PAK
8333        Pakistan  1987      Asia  Southern Asia   770  770   PAK  770  PAK
8334        Pakistan  1988      Asia  Southern Asia   770  770   PAK  770  PAK
8335        Pakistan  1989      Asia  Southern Asia   770  770   PAK  770  PAK
8336        Pakistan  1990      Asia  Southern Asia   770  770   PAK  770  PAK
8337        Pakistan  1991      Asia  Southern Asia   770  770   PAK  770  PAK
8338        Pakistan  1992      Asia  Southern Asia   770  770   PAK  770  PAK
8339        Pakistan  1993      Asia  Southern Asia   770  770   PAK  770  PAK
8340        Pakistan  1994      Asia  Southern Asia   770  770   PAK  770  PAK
8341        Pakistan  1995      Asia  Southern Asia   770  770   PAK  770  PAK
8342        Pakistan  1996      Asia  Southern Asia   770  770   PAK  770  PAK
8343        Pakistan  1997      Asia  Southern Asia   770  770   PAK  770  PAK
8344        Pakistan  1998      Asia  Southern Asia   770  770   PAK  770  PAK
8345        Pakistan  1999      Asia  Southern Asia   770  770   PAK  770  PAK
8346        Pakistan  2000      Asia  Southern Asia   770  770   PAK  770  PAK
8347        Pakistan  2001      Asia  Southern Asia   770  770   PAK  770  PAK
8348        Pakistan  2002      Asia  Southern Asia   770  770   PAK  770  PAK
8349        Pakistan  2003      Asia  Southern Asia   770  770   PAK  770  PAK
8350        Pakistan  2004      Asia  Southern Asia   770  770   PAK  770  PAK
8351        Pakistan  2005      Asia  Southern Asia   770  770   PAK  770  PAK
8352        Pakistan  2006      Asia  Southern Asia   770  770   PAK  770  PAK
8353        Pakistan  2007      Asia  Southern Asia   770  770   PAK  770  PAK
8354        Pakistan  2008      Asia  Southern Asia   770  770   PAK  770  PAK
8355        Pakistan  2009      Asia  Southern Asia   770  770   PAK  770  PAK
8356        Pakistan  2010      Asia  Southern Asia   770  770   PAK  770  PAK
8357        Pakistan  2011      Asia  Southern Asia   770  770   PAK  770  PAK
8358        Pakistan  2012      Asia  Southern Asia   770  770   PAK  770  PAK
8359        Pakistan  2013      Asia  Southern Asia   770  770   PAK  770  PAK
8360        Pakistan  2014      Asia  Southern Asia   770  770   PAK  770  PAK
8361        Pakistan  2015      Asia  Southern Asia   770  770   PAK  770  PAK
8362        Pakistan  2016      Asia  Southern Asia   770  770   PAK  770  PAK
8363        Pakistan  2017      Asia  Southern Asia   770  770   PAK  770  PAK
8364        Pakistan  2018      Asia  Southern Asia   770  770   PAK  770  PAK
8365        Pakistan  1947      Asia  Southern Asia   770  770   PAK  769  PAK
8366        Pakistan  1948      Asia  Southern Asia   770  770   PAK  769  PAK
8367        Pakistan  1949      Asia  Southern Asia   770  770   PAK  769  PAK
8368        Pakistan  1950      Asia  Southern Asia   770  770   PAK  769  PAK
8369        Pakistan  1951      Asia  Southern Asia   770  770   PAK  769  PAK
8370        Pakistan  1952      Asia  Southern Asia   770  770   PAK  769  PAK
8371        Pakistan  1953      Asia  Southern Asia   770  770   PAK  769  PAK
8372        Pakistan  1954      Asia  Southern Asia   770  770   PAK  769  PAK
8373        Pakistan  1955      Asia  Southern Asia   770  770   PAK  769  PAK
8374        Pakistan  1956      Asia  Southern Asia   770  770   PAK  769  PAK
8375        Pakistan  1957      Asia  Southern Asia   770  770   PAK  769  PAK
8376        Pakistan  1958      Asia  Southern Asia   770  770   PAK  769  PAK
8377        Pakistan  1959      Asia  Southern Asia   770  770   PAK  769  PAK
8378        Pakistan  1960      Asia  Southern Asia   770  770   PAK  769  PAK
8379        Pakistan  1961      Asia  Southern Asia   770  770   PAK  769  PAK
8380        Pakistan  1962      Asia  Southern Asia   770  770   PAK  769  PAK
8381        Pakistan  1963      Asia  Southern Asia   770  770   PAK  769  PAK
8382        Pakistan  1964      Asia  Southern Asia   770  770   PAK  769  PAK
8383        Pakistan  1965      Asia  Southern Asia   770  770   PAK  769  PAK
8384        Pakistan  1966      Asia  Southern Asia   770  770   PAK  769  PAK
8385        Pakistan  1967      Asia  Southern Asia   770  770   PAK  769  PAK
8386        Pakistan  1968      Asia  Southern Asia   770  770   PAK  769  PAK
8387        Pakistan  1969      Asia  Southern Asia   770  770   PAK  769  PAK
8388        Pakistan  1970      Asia  Southern Asia   770  770   PAK  769  PAK
8389        Pakistan  1971      Asia  Southern Asia   770  770   PAK  769  PAK

In [43]:
mask_ethiopia = cc['iso3c']=="ETH"
mask_ethiopia2 = (cc['iso3c']=="ETH") & (cc['year'] > 1993)
cc.loc[mask_ethiopia2, 'p4n'] = 529
cc[mask_ethiopia]

,country.name.en,year,continent,region,cown,gwn,iso3c,p4n,wb
3633,Ethiopia,1946,Africa,Eastern Africa,530,530,ETH,530,ETH
3634,Ethiopia,1947,Africa,Eastern Africa,530,530,ETH,530,ETH
3635,Ethiopia,1948,Africa,Eastern Africa,530,530,ETH,530,ETH
3636,Ethiopia,1949,Africa,Eastern Africa,530,530,ETH,530,ETH
3637,Ethiopia,1950,Africa,Eastern Africa,530,530,ETH,530,ETH
3638,Ethiopia,1951,Africa,Eastern Africa,530,530,ETH,530,ETH
3639,Ethiopia,1952,Africa,Eastern Africa,530,530,ETH,530,ETH
3640,Ethiopia,1953,Africa,Eastern Africa,530,530,ETH,530,ETH
3641,Ethiopia,1954,Africa,Eastern Africa,530,530,ETH,530,ETH
3642,Ethiopia,1955,Africa,Eastern Africa,530,530,ETH,530,ETH
3643,Ethiopia,1956,Africa,Eastern Africa,530,530,ETH,530,ETH
3644,Ethiopia,1957,Africa,Eastern Africa,530,530,ETH,530,ETH
3645,Ethiopia,1958,Africa,Eastern Africa,530,530,ETH,530,ETH
3646,Ethiopia,1959,Africa,Eastern Africa,530,530,ETH,530,ETH
3647,Ethiopia,1960,Africa,Eastern Africa,530,530,ETH,530,ETH
3648,Ethiopia,1961,Africa,Eastern Africa,530,530,ETH,530,ETH
3649,Ethiopia,1962,Africa,Eastern Africa,530,530,ETH,530,ETH
3650,Ethiopia,1963,Africa,Eastern Africa,530,530,ETH,530,ETH
3651,Ethiopia,1964,Africa,Eastern Africa,530,530,ETH,530,ETH
3652,Ethiopia,1965,Africa,Eastern Africa,530,530,ETH,530,ETH
3653,Ethiopia,1966,Africa,Eastern Africa,530,530,ETH,530,ETH
3654,Ethiopia,1967,Africa,Eastern Africa,530,530,ETH,530,ETH
3655,Ethiopia,1968,Africa,Eastern Africa,530,530,ETH,530,ETH
3656,Ethiopia,1969,Africa,Eastern Africa,530,530,ETH,530,ETH
3657,Ethiopia,1970,Africa,Eastern Africa,530,530,ETH,530,ETH
3658,Ethiopia,1971,Africa,Eastern Africa,530,530,ETH,530,ETH
3659,Ethiopia,1972,Africa,Eastern Africa,530,530,ETH,530,ETH
3660,Ethiopia,1973,Africa,Eastern Africa,530,530,ETH,530,ETH
3661,Ethiopia,1974,Africa,Eastern Africa,530,530,ETH,530,ETH
3662,Ethiopia,1975,Africa,Eastern Africa,530,530,ETH,530,ETH
3663,Ethiopia,1976,Africa,Eastern Africa,530,530,ETH,530,ETH
3664,Ethiopia,1977,Africa,Eastern Africa,530,530,ETH,530,ETH
3665,Ethiopia,1978,Africa,Eastern Africa,530,530,ETH,530,ETH
3666,Ethiopia,1979,Africa,Eastern Africa,530,530,ETH,530,ETH
3667,Ethiopia,1980,Africa,Eastern Africa,530,530,ETH,530,ETH
3668,Ethiopia,1981,Africa,Eastern Africa,530,530,ETH,530,ETH
3669,Ethiopia,1982,Africa,Eastern Africa,530,530,ETH,530,ETH
3670,Ethiopia,1983,Africa,Eastern Africa,530,530,ETH,530,ETH
3671,Ethiopia,1984,Africa,Eastern Africa,530,530,ETH,530,ETH
3672,Ethiopia,1985,Africa,Eastern Africa,530,530,ETH,530,ETH
3673,Ethiopia,1986,Africa,Eastern Africa,530,530,ETH,530,ETH
3674,Ethiopia,1987,Africa,Eastern Africa,530,530,ETH,530,ETH
3675,Ethiopia,1988,Africa,Eastern Africa,530,530,ETH,530,ETH
3676,Ethiopia,1989,Africa,Eastern Africa,530,530,ETH,530,ETH
3677,Ethiopia,1990,Africa,Eastern Africa,530,530,ETH,530,ETH
3678,Ethiopia,1991,Africa,Eastern Africa,530,530,ETH,530,ETH
3679,Ethiopia,1992,Africa,Eastern Africa,530,530,ETH,530,ETH
3680,Ethiopia,1993,Africa,Eastern Africa,530,530,ETH,530,ETH
3681,Ethiopia,1994,Africa,Eastern Africa,530,530,ETH,529,ETH
3682,Ethiopia,1995,Africa,Eastern Africa,530,530,ETH,529,ETH
3683,Ethiopia,1996,Africa,Eastern Africa,530,530,ETH,529,ETH
3684,Ethiopia,1997,Africa,Eastern Africa,530,530,ETH,529,ETH
3685,Ethiopia,1998,Africa,Eastern Africa,530,530,ETH,529,ETH
3686,Ethiopia,1999,Africa,Eastern Africa,530,530,ETH,529,ETH
3687,Ethiopia,2000,Africa,Eastern Africa,530,530,ETH,529,ETH
3688,Ethiopia,2001,Africa,Eastern Africa,530,530,ETH,529,ETH
3689,Ethiopia,2002,Africa,Eastern Africa,530,530,ETH,529,ETH
3690,Ethiopia,2003,Africa,Eastern Africa,530,530,ETH,529,ETH
3691,Ethiopia,2004,Africa,Eastern Africa,530,530,ETH,529,ETH
3692,Ethiopia,2005,Africa,Eastern Africa,530,530,ETH,529,ETH
3693,Ethiopia,2006,Africa,Eastern Africa,530,530,ETH,529,ETH
3694,Ethiopia,2007,Africa,Eastern Africa,530,530,ETH,529,ETH
3695,Ethiopia,2008,Africa,Eastern Africa,530,530,ETH,529,ETH
3696,Ethiopia,2009,Africa,Eastern Africa,530,530,ETH,529,ETH
3697,Ethiopia,2010,Africa,Eastern Africa,530,530,ETH,529,ETH
3698,Ethiopia,2011,Africa,Eastern Africa,530,530,ETH,529,ETH
3699,Ethiopia,2012,Africa,Eastern Africa,530,530,ETH,529,ETH
3700,Ethiopia,2013,Africa,Eastern Africa,530,530,ETH,529,ETH
3701,Ethiopia,2014,Africa,Eastern Africa,530,530,ETH,529,ETH
3702,Ethiopia,2015,Africa,Eastern Africa,530,530,ETH,529,ETH
3703,Ethiopia,2016,Africa,Eastern Africa,530,530,ETH,529,ETH
3704,Ethiopia,2017,Africa,Eastern Africa,530,530,ETH,529,ETH
3705,Ethiopia,2018,Africa,Eastern Africa,530,530,ETH,529,ETH

In [44]:
mask_ssudan = cc['iso3c']=="SSD"
cc.loc[mask_ssudan, 'p4n'] = 525
cc[mask_ssudan]

,country.name.en,year,continent,region,cown,gwn,iso3c,p4n,wb
10118,South Sudan,2011,Africa,Northern Africa,626,626,SSD,525,SSD
10119,South Sudan,2012,Africa,Northern Africa,626,626,SSD,525,SSD
10120,South Sudan,2013,Africa,Northern Africa,626,626,SSD,525,SSD
10121,South Sudan,2014,Africa,Northern Africa,626,626,SSD,525,SSD
10122,South Sudan,2015,Africa,Northern Africa,626,626,SSD,525,SSD
10123,South Sudan,2016,Africa,Northern Africa,626,626,SSD,525,SSD
10124,South Sudan,2017,Africa,Northern Africa,626,626,SSD,525,SSD
10125,South Sudan,2018,Africa,Northern Africa,626,626,SSD,525,SSD

In [45]:
mask_sudan = cc['iso3c']=="SDN"
mask_sudan2 = (cc['iso3c']=="SDN") & (cc['year'] > 2010)
cc.loc[mask_sudan2, 'p4n'] = 626
cc[mask_sudan]

,country.name.en,year,continent,region,cown,gwn,iso3c,p4n,wb
10409,Sudan,2012,Africa,Northern Africa,625,625,SDN,626,SDN
10410,Sudan,2013,Africa,Northern Africa,625,625,SDN,626,SDN
10411,Sudan,2014,Africa,Northern Africa,625,625,SDN,626,SDN
10412,Sudan,2015,Africa,Northern Africa,625,625,SDN,626,SDN
10413,Sudan,2016,Africa,Northern Africa,625,625,SDN,626,SDN
10414,Sudan,2017,Africa,Northern Africa,625,625,SDN,626,SDN
10415,Sudan,2018,Africa,Northern Africa,625,625,SDN,626,SDN
10416,Sudan,1956,Africa,Northern Africa,625,625,SDN,625,SDN
10417,Sudan,1957,Africa,Northern Africa,625,625,SDN,625,SDN
10418,Sudan,1958,Africa,Northern Africa,625,625,SDN,625,SDN
10419,Sudan,1959,Africa,Northern Africa,625,625,SDN,625,SDN
10420,Sudan,1960,Africa,Northern Africa,625,625,SDN,625,SDN
10421,Sudan,1961,Africa,Northern Africa,625,625,SDN,625,SDN
10422,Sudan,1962,Africa,Northern Africa,625,625,SDN,625,SDN
10423,Sudan,1963,Africa,Northern Africa,625,625,SDN,625,SDN
10424,Sudan,1964,Africa,Northern Africa,625,625,SDN,625,SDN
10425,Sudan,1965,Africa,Northern Africa,625,625,SDN,625,SDN
10426,Sudan,1966,Africa,Northern Africa,625,625,SDN,625,SDN
10427,Sudan,1967,Africa,Northern Africa,625,625,SDN,625,SDN
10428,Sudan,1968,Africa,Northern Africa,625,625,SDN,625,SDN
10429,Sudan,1969,Africa,Northern Africa,625,625,SDN,625,SDN
10430,Sudan,1970,Africa,Northern Africa,625,625,SDN,625,SDN
10431,Sudan,1971,Africa,Northern Africa,625,625,SDN,625,SDN
10432,Sudan,1972,Africa,Northern Africa,625,625,SDN,625,SDN
10433,Sudan,1973,Africa,Northern Africa,625,625,SDN,625,SDN
10434,Sudan,1974,Africa,Northern Africa,625,625,SDN,625,SDN
10435,Sudan,1975,Africa,Northern Africa,625,625,SDN,625,SDN
10436,Sudan,1976,Africa,Northern Africa,625,625,SDN,625,SDN
10437,Sudan,1977,Africa,Northern Africa,625,625,SDN,625,SDN
10438,Sudan,1978,Africa,Northern Africa,625,625,SDN,625,SDN
10439,Sudan,1979,Africa,Northern Africa,625,625,SDN,625,SDN
10440,Sudan,1980,Africa,Northern Africa,625,625,SDN,625,SDN
10441,Sudan,1981,Africa,Northern Africa,625,625,SDN,625,SDN
10442,Sudan,1982,Africa,Northern Africa,625,625,SDN,625,SDN
10443,Sudan,1983,Africa,Northern Africa,625,625,SDN,625,SDN
10444,Sudan,1984,Africa,Northern Africa,625,625,SDN,625,SDN
10445,Sudan,1985,Africa,Northern Africa,625,625,SDN,625,SDN
10446,Sudan,1986,Africa,Northern Africa,625,625,SDN,625,SDN
10447,Sudan,1987,Africa,Northern Africa,625,625,SDN,625,SDN
10448,Sudan,1988,Africa,Northern Africa,625,625,SDN,625,SDN
10449,Sudan,1989,Africa,Northern Africa,625,625,SDN,625,SDN
10450,Sudan,1990,Africa,Northern Africa,625,625,SDN,625,SDN
10451,Sudan,1991,Africa,Northern Africa,625,625,SDN,625,SDN
10452,Sudan,1992,Africa,Northern Africa,625,625,SDN,625,SDN
10453,Sudan,1993,Africa,Northern Africa,625,625,SDN,625,SDN
10454,Sudan,1994,Africa,Northern Africa,625,625,SDN,625,SDN
10455,Sudan,1995,Africa,Northern Africa,625,625,SDN,625,SDN
10456,Sudan,1996,Africa,Northern Africa,625,625,SDN,625,SDN
10457,Sudan,1997,Africa,Northern Africa,625,625,SDN,625,SDN
10458,Sudan,1998,Africa,Northern Africa,625,625,SDN,625,SDN
10459,Sudan,1999,Africa,Northern Africa,625,625,SDN,625,SDN
10460,Sudan,2000,Africa,Northern Africa,625,625,SDN,625,SDN
10461,Sudan,2001,Africa,Northern Africa,625,625,SDN,625,SDN
10462,Sudan,2002,Africa,Northern Africa,625,625,SDN,625,SDN
10463,Sudan,2003,Africa,Northern Africa,625,625,SDN,625,SDN
10464,Sudan,2004,Africa,Northern Africa,625,625,SDN,625,SDN
10465,Sudan,2005,Africa,Northern Africa,625,625,SDN,625,SDN
10466,Sudan,2006,Africa,Northern Africa,625,625,SDN,625,SDN
10467,Sudan,2007,Africa,Northern Africa,625,625,SDN,625,SDN
10468,Sudan,2008,Africa,Northern Africa,625,625,SDN,625,SDN
10469,Sudan,2009,Africa,Northern Africa,625,625,SDN,625,SDN
10470,Sudan,2010,Africa,Northern Africa,625,625,SDN,625,SDN
10471,Sudan,2011,Africa,Northern Africa,625,625,SDN,626,SDN
10472,Sudan,1946,Africa,Northern Africa,NaN,625,SDN,NaN,SDN
10473,Sudan,1947,Africa,Northern Africa,NaN,625,SDN,NaN,SDN
10474,Sudan,1948,Africa,Northern Africa,NaN,625,SDN,NaN,SDN
10475,Sudan,1949,Africa,Northern Africa,NaN,625,SDN,NaN,SDN
10476,Sudan,1950,Africa,Northern Africa,NaN,625,SDN,NaN,SDN
10477,Sudan,1951,Africa,Northern Africa,NaN,625,SDN,NaN,SDN
10478,Sudan,1952,Africa,Northern Africa,NaN,625,SDN,NaN,SDN
10479,Sudan,1953,Africa,Northern Africa,NaN,625,SDN,NaN,SDN
10480,Sudan,1954,Africa,Northern Africa,NaN,625,SDN,NaN,SDN
10481,Sudan,1955,Africa,Northern Africa,NaN,625,SDN,NaN,SDN

In [46]:
mask_somalia = cc['iso3c']=="SOM"
cc.loc[mask_somalia, 'wb'] = "SOM"
cc = cc[~(mask_somalia & cc['cown'].isna())]
cc[mask_somalia]

<ipython-input-46-a84c49ae83cc>:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  cc[mask_somalia]

,country.name.en,year,continent,region,cown,gwn,iso3c,p4n,wb
9899,Somalia,2008,Africa,Eastern Africa,520,520,SOM,520,SOM
9900,Somalia,2009,Africa,Eastern Africa,520,520,SOM,520,SOM
9901,Somalia,2010,Africa,Eastern Africa,520,520,SOM,520,SOM
9902,Somalia,2011,Africa,Eastern Africa,520,520,SOM,520,SOM
9903,Somalia,2012,Africa,Eastern Africa,520,520,SOM,520,SOM
9904,Somalia,2013,Africa,Eastern Africa,520,520,SOM,520,SOM
9905,Somalia,2014,Africa,Eastern Africa,520,520,SOM,520,SOM
9906,Somalia,2015,Africa,Eastern Africa,520,520,SOM,520,SOM
9907,Somalia,2016,Africa,Eastern Africa,520,520,SOM,520,SOM
9908,Somalia,2017,Africa,Eastern Africa,520,520,SOM,520,SOM
9909,Somalia,2018,Africa,Eastern Africa,520,520,SOM,520,SOM
9910,Somalia,1960,Africa,Eastern Africa,520,520,SOM,520,SOM
9911,Somalia,1961,Africa,Eastern Africa,520,520,SOM,520,SOM
9912,Somalia,1962,Africa,Eastern Africa,520,520,SOM,520,SOM
9913,Somalia,1963,Africa,Eastern Africa,520,520,SOM,520,SOM
9914,Somalia,1964,Africa,Eastern Africa,520,520,SOM,520,SOM
9915,Somalia,1965,Africa,Eastern Africa,520,520,SOM,520,SOM
9916,Somalia,1966,Africa,Eastern Africa,520,520,SOM,520,SOM
9917,Somalia,1967,Africa,Eastern Africa,520,520,SOM,520,SOM
9918,Somalia,1968,Africa,Eastern Africa,520,520,SOM,520,SOM
9919,Somalia,1969,Africa,Eastern Africa,520,520,SOM,520,SOM
9920,Somalia,1970,Africa,Eastern Africa,520,520,SOM,520,SOM
9921,Somalia,1971,Africa,Eastern Africa,520,520,SOM,520,SOM
9922,Somalia,1972,Africa,Eastern Africa,520,520,SOM,520,SOM
9923,Somalia,1973,Africa,Eastern Africa,520,520,SOM,520,SOM
9924,Somalia,1974,Africa,Eastern Africa,520,520,SOM,520,SOM
9925,Somalia,1975,Africa,Eastern Africa,520,520,SOM,520,SOM
9926,Somalia,1976,Africa,Eastern Africa,520,520,SOM,520,SOM
9927,Somalia,1977,Africa,Eastern Africa,520,520,SOM,520,SOM
9928,Somalia,1978,Africa,Eastern Africa,520,520,SOM,520,SOM
9929,Somalia,1979,Africa,Eastern Africa,520,520,SOM,520,SOM
9930,Somalia,1980,Africa,Eastern Africa,520,520,SOM,520,SOM
9931,Somalia,1981,Africa,Eastern Africa,520,520,SOM,520,SOM
9932,Somalia,1982,Africa,Eastern Africa,520,520,SOM,520,SOM
9933,Somalia,1983,Africa,Eastern Africa,520,520,SOM,520,SOM
9934,Somalia,1984,Africa,Eastern Africa,520,520,SOM,520,SOM
9935,Somalia,1985,Africa,Eastern Africa,520,520,SOM,520,SOM
9936,Somalia,1986,Africa,Eastern Africa,520,520,SOM,520,SOM
9937,Somalia,1987,Africa,Eastern Africa,520,520,SOM,520,SOM
9938,Somalia,1988,Africa,Eastern Africa,520,520,SOM,520,SOM
9939,Somalia,1989,Africa,Eastern Africa,520,520,SOM,520,SOM
9940,Somalia,1990,Africa,Eastern Africa,520,520,SOM,520,SOM
9941,Somalia,1991,Africa,Eastern Africa,520,520,SOM,520,SOM
9942,Somalia,1992,Africa,Eastern Africa,520,520,SOM,520,SOM
9943,Somalia,1993,Africa,Eastern Africa,520,520,SOM,520,SOM
9944,Somalia,1994,Africa,Eastern Africa,520,520,SOM,520,SOM
9945,Somalia,1995,Africa,Eastern Africa,520,520,SOM,520,SOM
9946,Somalia,1996,Africa,Eastern Africa,520,520,SOM,520,SOM
9947,Somalia,1997,Africa,Eastern Africa,520,520,SOM,520,SOM
9948,Somalia,1998,Africa,Eastern Africa,520,520,SOM,520,SOM
9949,Somalia,1999,Africa,Eastern Africa,520,520,SOM,520,SOM
9950,Somalia,2000,Africa,Eastern Africa,520,520,SOM,520,SOM
9951,Somalia,2001,Africa,Eastern Africa,520,520,SOM,520,SOM
9952,Somalia,2002,Africa,Eastern Africa,520,520,SOM,520,SOM
9953,Somalia,2003,Africa,Eastern Africa,520,520,SOM,520,SOM
9954,Somalia,2004,Africa,Eastern Africa,520,520,SOM,520,SOM
9955,Somalia,2005,Africa,Eastern Africa,520,520,SOM,520,SOM
9956,Somalia,2006,Africa,Eastern Africa,520,520,SOM,520,SOM
9957,Somalia,2007,Africa,Eastern Africa,520,520,SOM,520,SOM

In [47]:
mask_montenegro = cc['iso3c']=="MNE"
cc = cc[~(mask_montenegro & cc['cown'].isna())]
cc.loc[mask_montenegro, 'p4n'] = 348
cc[mask_montenegro]

<ipython-input-47-be11781f0430>:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  cc[mask_montenegro]

,country.name.en,year,continent,region,cown,gwn,iso3c,p4n,wb
7328,Montenegro,2006,Europe,Southern Europe,341,341,MNE,348,MNE
7329,Montenegro,2007,Europe,Southern Europe,341,341,MNE,348,MNE
7330,Montenegro,2008,Europe,Southern Europe,341,341,MNE,348,MNE
7331,Montenegro,2009,Europe,Southern Europe,341,341,MNE,348,MNE
7332,Montenegro,2010,Europe,Southern Europe,341,341,MNE,348,MNE
7333,Montenegro,2011,Europe,Southern Europe,341,341,MNE,348,MNE
7334,Montenegro,2012,Europe,Southern Europe,341,341,MNE,348,MNE
7335,Montenegro,2013,Europe,Southern Europe,341,341,MNE,348,MNE
7336,Montenegro,2014,Europe,Southern Europe,341,341,MNE,348,MNE
7337,Montenegro,2015,Europe,Southern Europe,341,341,MNE,348,MNE
7338,Montenegro,2016,Europe,Southern Europe,341,341,MNE,348,MNE
7339,Montenegro,2017,Europe,Southern Europe,341,341,MNE,348,MNE
7340,Montenegro,2018,Europe,Southern Europe,341,341,MNE,348,MNE

In [48]:
mask_kosovo = cc['country.name.en']=="Kosovo"
cc = cc[~(mask_kosovo & cc['cown'].isna())]
cc.loc[mask_kosovo, 'p4n'] = 341
cc.loc[mask_kosovo, 'iso3c'] = "XKX"
cc.loc[mask_kosovo, 'continent'] = "Europe"
cc.loc[mask_kosovo, 'region'] = "Southern Europe"
cc[mask_kosovo]

<ipython-input-48-62dcd888fa95>:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  cc[mask_kosovo]

,country.name.en,year,continent,region,cown,gwn,iso3c,p4n,wb
5835,Kosovo,2008,Europe,Southern Europe,347,347,XKX,341,XKX
5836,Kosovo,2009,Europe,Southern Europe,347,347,XKX,341,XKX
5837,Kosovo,2010,Europe,Southern Europe,347,347,XKX,341,XKX
5838,Kosovo,2011,Europe,Southern Europe,347,347,XKX,341,XKX
5839,Kosovo,2012,Europe,Southern Europe,347,347,XKX,341,XKX
5840,Kosovo,2013,Europe,Southern Europe,347,347,XKX,341,XKX
5841,Kosovo,2014,Europe,Southern Europe,347,347,XKX,341,XKX
5842,Kosovo,2015,Europe,Southern Europe,347,347,XKX,341,XKX
5843,Kosovo,2016,Europe,Southern Europe,347,347,XKX,341,XKX
5844,Kosovo,2017,Europe,Southern Europe,347,347,XKX,341,XKX
5845,Kosovo,2018,Europe,Southern Europe,347,347,XKX,341,XKX

In [49]:
mask_yugoslavia = cc['country.name.en']=="Yugoslavia"

mask_yugoslavia2 = (cc['country.name.en']=="Yugoslavia") & (cc['year'] > 1990)
mask_yugoslavia3 = (cc['country.name.en']=="Yugoslavia") & (cc['year'] > 2007)

cc = cc[~(mask_yugoslavia3)]
cc.loc[mask_yugoslavia2, 'p4n'] = 347
cc.loc[mask_yugoslavia, 'iso3c'] = "YUG"
cc.loc[mask_yugoslavia, 'wb'] = "SRB"
cc.loc[mask_yugoslavia, 'continent'] = "Europe"
cc.loc[mask_yugoslavia, 'region'] = "Southern Europe"

cc[mask_yugoslavia]

<ipython-input-49-6b1dfde07648>:13: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  cc[mask_yugoslavia]

,country.name.en,year,continent,region,cown,gwn,iso3c,p4n,wb
12235,Yugoslavia,1992,Europe,Southern Europe,345,345,YUG,347,SRB
12236,Yugoslavia,1993,Europe,Southern Europe,345,345,YUG,347,SRB
12237,Yugoslavia,1994,Europe,Southern Europe,345,345,YUG,347,SRB
12238,Yugoslavia,1995,Europe,Southern Europe,345,345,YUG,347,SRB
12239,Yugoslavia,1996,Europe,Southern Europe,345,345,YUG,347,SRB
12240,Yugoslavia,1997,Europe,Southern Europe,345,345,YUG,347,SRB
12241,Yugoslavia,1998,Europe,Southern Europe,345,345,YUG,347,SRB
12242,Yugoslavia,1999,Europe,Southern Europe,345,345,YUG,347,SRB
12243,Yugoslavia,2000,Europe,Southern Europe,345,345,YUG,347,SRB
12244,Yugoslavia,2001,Europe,Southern Europe,345,345,YUG,347,SRB
12245,Yugoslavia,2002,Europe,Southern Europe,345,345,YUG,347,SRB
12246,Yugoslavia,1946,Europe,Southern Europe,345,345,YUG,345,SRB
12247,Yugoslavia,1947,Europe,Southern Europe,345,345,YUG,345,SRB
12248,Yugoslavia,1948,Europe,Southern Europe,345,345,YUG,345,SRB
12249,Yugoslavia,1949,Europe,Southern Europe,345,345,YUG,345,SRB
12250,Yugoslavia,1950,Europe,Southern Europe,345,345,YUG,345,SRB
12251,Yugoslavia,1951,Europe,Southern Europe,345,345,YUG,345,SRB
12252,Yugoslavia,1952,Europe,Southern Europe,345,345,YUG,345,SRB
12253,Yugoslavia,1953,Europe,Southern Europe,345,345,YUG,345,SRB
12254,Yugoslavia,1954,Europe,Southern Europe,345,345,YUG,345,SRB
12255,Yugoslavia,1955,Europe,Southern Europe,345,345,YUG,345,SRB
12256,Yugoslavia,1956,Europe,Southern Europe,345,345,YUG,345,SRB
12257,Yugoslavia,1957,Europe,Southern Europe,345,345,YUG,345,SRB
12258,Yugoslavia,1958,Europe,Southern Europe,345,345,YUG,345,SRB
12259,Yugoslavia,1959,Europe,Southern Europe,345,345,YUG,345,SRB
12260,Yugoslavia,1960,Europe,Southern Europe,345,345,YUG,345,SRB
12261,Yugoslavia,1961,Europe,Southern Europe,345,345,YUG,345,SRB
12262,Yugoslavia,1962,Europe,Southern Europe,345,345,YUG,345,SRB
12263,Yugoslavia,1963,Europe,Southern Europe,345,345,YUG,345,SRB
12264,Yugoslavia,1964,Europe,Southern Europe,345,345,YUG,345,SRB
12265,Yugoslavia,1965,Europe,Southern Europe,345,345,YUG,345,SRB
12266,Yugoslavia,1966,Europe,Southern Europe,345,345,YUG,345,SRB
12267,Yugoslavia,1967,Europe,Southern Europe,345,345,YUG,345,SRB
12268,Yugoslavia,1968,Europe,Southern Europe,345,345,YUG,345,SRB
12269,Yugoslavia,1969,Europe,Southern Europe,345,345,YUG,345,SRB
12270,Yugoslavia,1970,Europe,Southern Europe,345,345,YUG,345,SRB
12271,Yugoslavia,1971,Europe,Southern Europe,345,345,YUG,345,SRB
12272,Yugoslavia,1972,Europe,Southern Europe,345,345,YUG,345,SRB
12273,Yugoslavia,1973,Europe,Southern Europe,345,345,YUG,345,SRB
12274,Yugoslavia,1974,Europe,Southern Europe,345,345,YUG,345,SRB
12275,Yugoslavia,1975,Europe,Southern Europe,345,345,YUG,345,SRB
12276,Yugoslavia,1976,Europe,Southern Europe,345,345,YUG,345,SRB
12277,Yugoslavia,1977,Europe,Southern Europe,345,345,YUG,345,SRB
12278,Yugoslavia,1978,Europe,Southern Europe,345,345,YUG,345,SRB
12279,Yugoslavia,1979,Europe,Southern Europe,345,345,YUG,345,SRB
12280,Yugoslavia,1980,Europe,Southern Europe,345,345,YUG,345,SRB
12281,Yugoslavia,1981,Europe,Southern Europe,345,345,YUG,345,SRB
12282,Yugoslavia,1982,Europe,Southern Europe,345,345,YUG,345,SRB
12283,Yugoslavia,1983,Europe,Southern Europe,345,345,YUG,345,SRB
12284,Yugoslavia,1984,Europe,Southern Europe,345,345,YUG,345,SRB
12285,Yugoslavia,1985,Europe,Southern Europe,345,345,YUG,345,SRB
12286,Yugoslavia,1986,Europe,Southern Europe,345,345,YUG,345,SRB
12287,Yugoslavia,1987,Europe,Southern Europe,345,345,YUG,345,SRB
12288,Yugoslavia,1988,Europe,Southern Europe,345,345,YUG,345,SRB
12289,Yugoslavia,1989,Europe,Southern Europe,345,345,YUG,345,SRB
12290,Yugoslavia,1990,Europe,Southern Europe,345,345,YUG,345,SRB
12291,Yugoslavia,1991,Europe,Southern Europe,345,345,YUG,347,SRB
12292,Yugoslavia,2003,Europe,Southern Europe,345,345,YUG,347,SRB
12293,Yugoslavia,2004,Europe,Southern Europe,345,345,YUG,347,SRB
12294,Yugoslavia,2005,Europe,Southern Europe,345,345,YUG,347,SRB
12295,Yugoslavia,2006,Europe,Southern Europe,345,345,YUG,347,SRB
12296,Yugoslavia,2007,Europe,Southern Europe,345,345,YUG,347,SRB

In [50]:
mask_serbia = cc['country.name.en']=="Serbia"
mask_serbia_drop = (cc['country.name.en']=="Serbia") & (cc['year'] < 2006)

cc = cc[~(mask_serbia_drop)]
cc.loc[mask_serbia, 'cown'] = 345

cc[mask_serbia]

<ipython-input-50-7d00c8e93176>:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  cc[mask_serbia]

,country.name.en,year,continent,region,cown,gwn,iso3c,p4n,wb
9478,Serbia,2010,Europe,Southern Europe,345,340,SRB,342,SRB
9479,Serbia,2011,Europe,Southern Europe,345,340,SRB,342,SRB
9480,Serbia,2012,Europe,Southern Europe,345,340,SRB,342,SRB
9481,Serbia,2013,Europe,Southern Europe,345,340,SRB,342,SRB
9482,Serbia,2014,Europe,Southern Europe,345,340,SRB,342,SRB
9483,Serbia,2015,Europe,Southern Europe,345,340,SRB,342,SRB
9484,Serbia,2016,Europe,Southern Europe,345,340,SRB,342,SRB
9485,Serbia,2017,Europe,Southern Europe,345,340,SRB,342,SRB
9486,Serbia,2018,Europe,Southern Europe,345,340,SRB,342,SRB
9504,Serbia,2006,Europe,Southern Europe,345,340,SRB,342,SRB
9505,Serbia,2007,Europe,Southern Europe,345,340,SRB,342,SRB
9506,Serbia,2008,Europe,Southern Europe,345,340,SRB,342,SRB
9507,Serbia,2009,Europe,Southern Europe,345,340,SRB,342,SRB

## Compare to base G&W time series

note: countrycode isn't filling in the G&W codes correctly - filling in values where country doesn't yet exist

In [51]:
gw['StartDate'] = gw['gw_startdate'].apply(lambda dt: dt.replace(day=1, month=1))
gw['EndDate'] = gw['gw_enddate'].apply(lambda dt: dt.replace(day=1, month=1))


gw_ts = pd.concat([pd.DataFrame({'year': pd.date_range(row.StartDate, row.EndDate, freq='YS'),
                                 'gwn': row.gw_id}, 
                                 columns=['year', 'gwn']) 
                                 for i, row in gw.iterrows()], ignore_index=True)
gw_ts['year'] = gw_ts['year'].dt.year
gw_ts = gw_ts[gw_ts['year'] > 1945].reset_index(drop=True)
gw_ts['in_gw'] = 1
gw_ts

<ipython-input-51-7808074061d7>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gw['StartDate'] = gw['gw_startdate'].apply(lambda dt: dt.replace(day=1, month=1))
<ipython-input-51-7808074061d7>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gw['EndDate'] = gw['gw_enddate'].apply(lambda dt: dt.replace(day=1, month=1))

       year  gwn  in_gw
0      1946    2      1
1      1947    2      1
2      1948    2      1
3      1949    2      1
4      1950    2      1
...     ...  ...    ...
11123  2013  990      1
11124  2014  990      1
11125  2015  990      1
11126  2016  990      1
11127  2017  990      1

[11128 rows x 3 columns]

In [52]:
gw_ts['gwn'] = gw_ts['gwn'].astype('Int64')
cc_check_gw = cc.merge(gw_ts, on=['year', 'gwn'], how='outer')
cc_check_gw

,country.name.en,year,continent,region,cown,gwn,iso3c,p4n,wb,in_gw
0,Afghanistan,1946,Asia,Southern Asia,700,700,AFG,700,AFG,1.0
1,Afghanistan,1947,Asia,Southern Asia,700,700,AFG,700,AFG,1.0
2,Afghanistan,1948,Asia,Southern Asia,700,700,AFG,700,AFG,1.0
3,Afghanistan,1949,Asia,Southern Asia,700,700,AFG,700,AFG,1.0
4,Afghanistan,1950,Asia,Southern Asia,700,700,AFG,700,AFG,1.0
...,...,...,...,...,...,...,...,...,...,...
12847,NaN,1971,NaN,NaN,NaN,990,NaN,NaN,NaN,1.0
12848,NaN,1972,NaN,NaN,NaN,990,NaN,NaN,NaN,1.0
12849,NaN,1973,NaN,NaN,NaN,990,NaN,NaN,NaN,1.0
12850,NaN,1974,NaN,NaN,NaN,990,NaN,NaN,NaN,1.0
12851,NaN,1975,NaN,NaN,NaN,990,NaN,NaN,NaN,1.0

find countries that exist in G&W but not in countrycode

Yemen & Vietnam are the only ones that need G&W codes added; rest are microstates

In [53]:
cc_check_gw[cc_check_gw['country.name.en'].isna()]['gwn'].unique()

array([678, 711, 816, 221, 223, 331, 232, 396, 397, 403, 970, 971, 972,
       973, 983, 987, 990], dtype=object)

#### Need to fix Yemen

- Where cown is 679, fill gwn NAs with 678

In [54]:
cc_check_gw[cc_check_gw['gwn']==678]

,country.name.en,year,continent,region,cown,gwn,iso3c,p4n,wb,in_gw
12075,Yemen Arab Republic,1946,NaN,NaN,678,678,NaN,678,NaN,1.0
12076,Yemen Arab Republic,1947,NaN,NaN,678,678,NaN,678,NaN,1.0
12077,Yemen Arab Republic,1948,NaN,NaN,678,678,NaN,678,NaN,1.0
12078,Yemen Arab Republic,1949,NaN,NaN,678,678,NaN,678,NaN,1.0
12079,Yemen Arab Republic,1950,NaN,NaN,678,678,NaN,678,NaN,1.0
12080,Yemen Arab Republic,1951,NaN,NaN,678,678,NaN,678,NaN,1.0
12081,Yemen Arab Republic,1952,NaN,NaN,678,678,NaN,678,NaN,1.0
12082,Yemen Arab Republic,1953,NaN,NaN,678,678,NaN,678,NaN,1.0
12083,Yemen Arab Republic,1954,NaN,NaN,678,678,NaN,678,NaN,1.0
12084,Yemen Arab Republic,1955,NaN,NaN,678,678,NaN,678,NaN,1.0
12085,Yemen Arab Republic,1956,NaN,NaN,678,678,NaN,678,NaN,1.0
12086,Yemen Arab Republic,1957,NaN,NaN,678,678,NaN,678,NaN,1.0
12087,Yemen Arab Republic,1958,NaN,NaN,678,678,NaN,678,NaN,1.0
12088,Yemen Arab Republic,1959,NaN,NaN,678,678,NaN,678,NaN,1.0
12089,Yemen Arab Republic,1960,NaN,NaN,678,678,NaN,678,NaN,1.0
12090,Yemen Arab Republic,1961,NaN,NaN,678,678,NaN,678,NaN,1.0
12091,Yemen Arab Republic,1962,NaN,NaN,678,678,NaN,678,NaN,1.0
12092,Yemen Arab Republic,1963,NaN,NaN,678,678,NaN,678,NaN,1.0
12093,Yemen Arab Republic,1964,NaN,NaN,678,678,NaN,678,NaN,1.0
12094,Yemen Arab Republic,1965,NaN,NaN,678,678,NaN,678,NaN,1.0
12095,Yemen Arab Republic,1966,NaN,NaN,678,678,NaN,678,NaN,1.0
12096,Yemen Arab Republic,1967,NaN,NaN,678,678,NaN,678,NaN,1.0
12097,Yemen Arab Republic,1968,NaN,NaN,678,678,NaN,678,NaN,1.0
12098,Yemen Arab Republic,1969,NaN,NaN,678,678,NaN,678,NaN,1.0
12099,Yemen Arab Republic,1970,NaN,NaN,678,678,NaN,678,NaN,1.0
12100,Yemen Arab Republic,1971,NaN,NaN,678,678,NaN,678,NaN,1.0
12101,Yemen Arab Republic,1972,NaN,NaN,678,678,NaN,678,NaN,1.0
12102,Yemen Arab Republic,1973,NaN,NaN,678,678,NaN,678,NaN,1.0
12103,Yemen Arab Republic,1974,NaN,NaN,678,678,NaN,678,NaN,1.0
12104,Yemen Arab Republic,1975,NaN,NaN,678,678,NaN,678,NaN,1.0
12105,Yemen Arab Republic,1976,NaN,NaN,678,678,NaN,678,NaN,1.0
12106,Yemen Arab Republic,1977,NaN,NaN,678,678,NaN,678,NaN,1.0
12107,Yemen Arab Republic,1978,NaN,NaN,678,678,NaN,678,NaN,1.0
12108,Yemen Arab Republic,1979,NaN,NaN,678,678,NaN,678,NaN,1.0
12109,Yemen Arab Republic,1980,NaN,NaN,678,678,NaN,678,NaN,1.0
12110,Yemen Arab Republic,1981,NaN,NaN,678,678,NaN,678,NaN,1.0
12111,Yemen Arab Republic,1982,NaN,NaN,678,678,NaN,678,NaN,1.0
12112,Yemen Arab Republic,1983,NaN,NaN,678,678,NaN,678,NaN,1.0
12113,Yemen Arab Republic,1984,NaN,NaN,678,678,NaN,678,NaN,1.0
12114,Yemen Arab Republic,1985,NaN,NaN,678,678,NaN,678,NaN,1.0
12115,Yemen Arab Republic,1986,NaN,NaN,678,678,NaN,678,NaN,1.0
12116,Yemen Arab Republic,1987,NaN,NaN,678,678,NaN,678,NaN,1.0
12117,Yemen Arab Republic,1988,NaN,NaN,678,678,NaN,678,NaN,1.0
12118,Yemen Arab Republic,1989,NaN,NaN,678,678,NaN,678,NaN,1.0
12119,Yemen Arab Republic,1990,NaN,NaN,678,678,NaN,678,NaN,1.0
12425,NaN,1991,NaN,NaN,NaN,678,NaN,NaN,NaN,1.0
12426,NaN,1992,NaN,NaN,NaN,678,NaN,NaN,NaN,1.0
12427,NaN,1993,NaN,NaN,NaN,678,NaN,NaN,NaN,1.0
12428,NaN,1994,NaN,NaN,NaN,678,NaN,NaN,NaN,1.0
12429,NaN,1995,NaN,NaN,NaN,678,NaN,NaN,NaN,1.0
12430,NaN,1996,NaN,NaN,NaN,678,NaN,NaN,NaN,1.0
12431,NaN,1997,NaN,NaN,NaN,678,NaN,NaN,NaN,1.0
12432,NaN,1998,NaN,NaN,NaN,678,NaN,NaN,NaN,1.0
12433,NaN,1999,NaN,NaN,NaN,678,NaN,NaN,NaN,1.0
12434,NaN,2000,NaN,NaN,NaN,678,NaN,NaN,NaN,1.0
12435,NaN,2001,NaN,NaN,NaN,678,NaN,NaN,NaN,1.0
12436,NaN,2002,NaN,NaN,NaN,678,NaN,NaN,NaN,1.0
12437,NaN,2003,NaN,NaN,NaN,678,NaN,NaN,NaN,1.0
12438,NaN,2004,NaN,NaN,NaN,678,NaN,NaN,NaN,1.0
12439,NaN,2005,NaN,NaN,NaN,678,NaN,NaN,NaN,1.0
12440,NaN,2006,NaN,NaN,NaN,678,NaN,NaN,NaN,1.0
12441,NaN,2007,NaN,NaN,NaN,678,NaN,NaN,NaN,1.0
12442,NaN,2008,NaN,NaN,NaN,678,NaN,NaN,NaN,1.0
12443,NaN,2009,NaN,NaN,NaN,678,NaN,NaN,NaN,1.0
12444,NaN,2010,NaN,NaN,NaN,678,NaN,NaN,NaN,1.0
12445,NaN,2011,NaN,NaN,NaN,678,NaN,NaN,NaN,1.0
12446,NaN,2012,NaN,NaN,NaN,678,NaN,NaN,NaN,1.0
12447,NaN,2013,NaN,NaN,NaN,678,NaN,NaN,NaN,1.0
12448,NaN,2014,NaN,NaN,NaN,678,NaN,NaN,NaN,1.0
12449,NaN,2015,NaN,NaN,NaN,678,NaN,NaN,NaN,1.0
12450,NaN,2016,NaN,NaN,NaN,678,NaN,NaN,NaN,1.0
12451,NaN,2017,NaN,NaN,NaN,678,NaN,NaN,NaN,1.0

In [55]:
mask_yemen = cc_check_gw['cown']==679

cc_check_gw.loc[mask_yemen, 'gwn'] = cc_check_gw.loc[mask_yemen, 'gwn'].fillna(678)

#### can't fix Vietnam

for some reason countrycode doesn't count North Vietnam, and this isn't something I can readily fix without potentially messing up other merges.

In [56]:
cc_check_gw[cc_check_gw['gwn']==816]

,country.name.en,year,continent,region,cown,gwn,iso3c,p4n,wb,in_gw
12032,Vietnam,2018,Asia,South-Eastern Asia,816,816,VNM,818,VNM,NaN
12033,Vietnam,2010,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12034,Vietnam,2011,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12035,Vietnam,2016,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12036,Vietnam,2017,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12037,Vietnam,1978,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12038,Vietnam,1979,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12039,Vietnam,1980,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12040,Vietnam,1981,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12041,Vietnam,1982,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12042,Vietnam,1983,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12043,Vietnam,1976,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12044,Vietnam,1977,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12045,Vietnam,1984,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12046,Vietnam,1985,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12047,Vietnam,1986,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12048,Vietnam,1987,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12049,Vietnam,1988,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12050,Vietnam,1989,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12051,Vietnam,1990,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12052,Vietnam,1991,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12053,Vietnam,1992,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12054,Vietnam,1993,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12055,Vietnam,2003,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12056,Vietnam,2004,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12057,Vietnam,2005,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12058,Vietnam,2006,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12059,Vietnam,2007,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12060,Vietnam,2008,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12061,Vietnam,2009,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12062,Vietnam,2012,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12063,Vietnam,2013,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12064,Vietnam,2014,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12065,Vietnam,2015,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12066,Vietnam,2002,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12067,Vietnam,1994,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12068,Vietnam,1995,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12069,Vietnam,2001,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12070,Vietnam,1996,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12071,Vietnam,1998,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12072,Vietnam,1999,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12073,Vietnam,2000,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12074,Vietnam,1997,Asia,South-Eastern Asia,816,816,VNM,818,VNM,1.0
12457,NaN,1954,NaN,NaN,NaN,816,NaN,NaN,NaN,1.0
12458,NaN,1955,NaN,NaN,NaN,816,NaN,NaN,NaN,1.0
12459,NaN,1956,NaN,NaN,NaN,816,NaN,NaN,NaN,1.0
12460,NaN,1957,NaN,NaN,NaN,816,NaN,NaN,NaN,1.0
12461,NaN,1958,NaN,NaN,NaN,816,NaN,NaN,NaN,1.0
12462,NaN,1959,NaN,NaN,NaN,816,NaN,NaN,NaN,1.0
12463,NaN,1960,NaN,NaN,NaN,816,NaN,NaN,NaN,1.0
12464,NaN,1961,NaN,NaN,NaN,816,NaN,NaN,NaN,1.0
12465,NaN,1962,NaN,NaN,NaN,816,NaN,NaN,NaN,1.0
12466,NaN,1963,NaN,NaN,NaN,816,NaN,NaN,NaN,1.0
12467,NaN,1964,NaN,NaN,NaN,816,NaN,NaN,NaN,1.0
12468,NaN,1965,NaN,NaN,NaN,816,NaN,NaN,NaN,1.0
12469,NaN,1966,NaN,NaN,NaN,816,NaN,NaN,NaN,1.0
12470,NaN,1967,NaN,NaN,NaN,816,NaN,NaN,NaN,1.0
12471,NaN,1968,NaN,NaN,NaN,816,NaN,NaN,NaN,1.0
12472,NaN,1969,NaN,NaN,NaN,816,NaN,NaN,NaN,1.0
12473,NaN,1970,NaN,NaN,NaN,816,NaN,NaN,NaN,1.0
12474,NaN,1971,NaN,NaN,NaN,816,NaN,NaN,NaN,1.0
12475,NaN,1972,NaN,NaN,NaN,816,NaN,NaN,NaN,1.0
12476,NaN,1973,NaN,NaN,NaN,816,NaN,NaN,NaN,1.0
12477,NaN,1974,NaN,NaN,NaN,816,NaN,NaN,NaN,1.0
12478,NaN,1975,NaN,NaN,NaN,816,NaN,NaN,NaN,1.0

find countries that exist in countrycode but not in G&W

In [57]:
mask_valid_gw = (cc_check_gw['in_gw'].isna()) & (cc_check_gw['year'] < 2018)
cc_check_gw[mask_valid_gw]['gwn'].unique()

array([615, 540, 371, 373, 692, 53, 370, 434, 760, 571, 439, 516, 811,
       402, 482, 483, 581, 484, 490, 437, 344, 352, 316, 522, 54, 265,
       411, 531, 366, 950, 481, 420, 372, 260, 452, 438, 404, 110, 750,
       51, 705, 501, 690, 703, 812, 367, 570, 368, 580, 553, 820, 781,
       432, 435, 590, 359, 600, 541, 775, 565, 436, 475, 731, 910, 694,
       517, nan, 678, 433, 591, 451, 830, 349, 940, 732, 680, 780, 625,
       115, 572, 713, 702, 510, 860, 461, 52, 616, 701, 500, 369, 704,
       935, 345, 551, 511, 552], dtype=object)

In [58]:
cc_check_gw[mask_valid_gw].head(100)

,country.name.en,year,continent,region,cown,gwn,iso3c,p4n,wb,in_gw
203,Algeria,1956,Africa,Northern Africa,NaN,615,DZA,NaN,DZA,NaN
204,Algeria,1957,Africa,Northern Africa,NaN,615,DZA,NaN,DZA,NaN
205,Algeria,1958,Africa,Northern Africa,NaN,615,DZA,NaN,DZA,NaN
206,Algeria,1959,Africa,Northern Africa,NaN,615,DZA,NaN,DZA,NaN
207,Algeria,1960,Africa,Northern Africa,NaN,615,DZA,NaN,DZA,NaN
208,Algeria,1961,Africa,Northern Africa,NaN,615,DZA,NaN,DZA,NaN
209,Algeria,1946,Africa,Northern Africa,NaN,615,DZA,NaN,DZA,NaN
210,Algeria,1947,Africa,Northern Africa,NaN,615,DZA,NaN,DZA,NaN
211,Algeria,1948,Africa,Northern Africa,NaN,615,DZA,NaN,DZA,NaN
212,Algeria,1949,Africa,Northern Africa,NaN,615,DZA,NaN,DZA,NaN
213,Algeria,1950,Africa,Northern Africa,NaN,615,DZA,NaN,DZA,NaN
214,Algeria,1951,Africa,Northern Africa,NaN,615,DZA,NaN,DZA,NaN
215,Algeria,1952,Africa,Northern Africa,NaN,615,DZA,NaN,DZA,NaN
216,Algeria,1953,Africa,Northern Africa,NaN,615,DZA,NaN,DZA,NaN
217,Algeria,1954,Africa,Northern Africa,NaN,615,DZA,NaN,DZA,NaN
218,Algeria,1955,Africa,Northern Africa,NaN,615,DZA,NaN,DZA,NaN
289,Angola,1946,Africa,Middle Africa,NaN,540,AGO,NaN,AGO,NaN
290,Angola,1947,Africa,Middle Africa,NaN,540,AGO,NaN,AGO,NaN
291,Angola,1948,Africa,Middle Africa,NaN,540,AGO,NaN,AGO,NaN
292,Angola,1949,Africa,Middle Africa,NaN,540,AGO,NaN,AGO,NaN
293,Angola,1950,Africa,Middle Africa,NaN,540,AGO,NaN,AGO,NaN
294,Angola,1951,Africa,Middle Africa,NaN,540,AGO,NaN,AGO,NaN
295,Angola,1952,Africa,Middle Africa,NaN,540,AGO,NaN,AGO,NaN
296,Angola,1953,Africa,Middle Africa,NaN,540,AGO,NaN,AGO,NaN
297,Angola,1954,Africa,Middle Africa,NaN,540,AGO,NaN,AGO,NaN
298,Angola,1955,Africa,Middle Africa,NaN,540,AGO,NaN,AGO,NaN
299,Angola,1956,Africa,Middle Africa,NaN,540,AGO,NaN,AGO,NaN
300,Angola,1957,Africa,Middle Africa,NaN,540,AGO,NaN,AGO,NaN
301,Angola,1958,Africa,Middle Africa,NaN,540,AGO,NaN,AGO,NaN
302,Angola,1959,Africa,Middle Africa,NaN,540,AGO,NaN,AGO,NaN
303,Angola,1960,Africa,Middle Africa,NaN,540,AGO,NaN,AGO,NaN
304,Angola,1961,Africa,Middle Africa,NaN,540,AGO,NaN,AGO,NaN
305,Angola,1962,Africa,Middle Africa,NaN,540,AGO,NaN,AGO,NaN
306,Angola,1963,Africa,Middle Africa,NaN,540,AGO,NaN,AGO,NaN
307,Angola,1964,Africa,Middle Africa,NaN,540,AGO,NaN,AGO,NaN
308,Angola,1965,Africa,Middle Africa,NaN,540,AGO,NaN,AGO,NaN
309,Angola,1966,Africa,Middle Africa,NaN,540,AGO,NaN,AGO,NaN
310,Angola,1967,Africa,Middle Africa,NaN,540,AGO,NaN,AGO,NaN
311,Angola,1968,Africa,Middle Africa,NaN,540,AGO,NaN,AGO,NaN
312,Angola,1969,Africa,Middle Africa,NaN,540,AGO,NaN,AGO,NaN
313,Angola,1970,Africa,Middle Africa,NaN,540,AGO,NaN,AGO,NaN
314,Angola,1971,Africa,Middle Africa,NaN,540,AGO,NaN,AGO,NaN
315,Angola,1972,Africa,Middle Africa,NaN,540,AGO,NaN,AGO,NaN
316,Angola,1973,Africa,Middle Africa,NaN,540,AGO,NaN,AGO,NaN
317,Angola,1974,Africa,Middle Africa,NaN,540,AGO,NaN,AGO,NaN
457,Armenia,1990,Asia,Western Asia,NaN,371,ARM,NaN,ARM,NaN
632,Azerbaijan,1990,Asia,Western Asia,NaN,373,AZE,NaN,AZE,NaN
727,Bahrain,1946,Asia,Western Asia,NaN,692,BHR,NaN,BHR,NaN
728,Bahrain,1947,Asia,Western Asia,NaN,692,BHR,NaN,BHR,NaN
729,Bahrain,1948,Asia,Western Asia,NaN,692,BHR,NaN,BHR,NaN
730,Bahrain,1949,Asia,Western Asia,NaN,692,BHR,NaN,BHR,NaN
731,Bahrain,1950,Asia,Western Asia,NaN,692,BHR,NaN,BHR,NaN
732,Bahrain,1951,Asia,Western Asia,NaN,692,BHR,NaN,BHR,NaN
733,Bahrain,1952,Asia,Western Asia,NaN,692,BHR,NaN,BHR,NaN
734,Bahrain,1953,Asia,Western Asia,NaN,692,BHR,NaN,BHR,NaN
735,Bahrain,1954,Asia,Western Asia,NaN,692,BHR,NaN,BHR,NaN
736,Bahrain,1955,Asia,Western Asia,NaN,692,BHR,NaN,BHR,NaN
737,Bahrain,1956,Asia,Western Asia,NaN,692,BHR,NaN,BHR,NaN
738,Bahrain,1957,Asia,Western Asia,NaN,692,BHR,NaN,BHR,NaN
739,Bahrain,1958,Asia,Western Asia,NaN,692,BHR,NaN,BHR,NaN
740,Bahrain,1959,Asia,Western Asia,NaN,692,BHR,NaN,BHR,NaN
741,Bahrain,1960,Asia,Western Asia,NaN,692,BHR,NaN,BHR,NaN
742,Bahrain,1961,Asia,Western Asia,NaN,692,BHR,NaN,BHR,NaN
743,Bahrain,1962,Asia,Western Asia,NaN,692,BHR,NaN,BHR,NaN
744,Bahrain,1963,Asia,Western Asia,NaN,692,BHR,NaN,BHR,NaN
745,Bahrain,1964,Asia,Western Asia,NaN,692,BHR,NaN,BHR,NaN
746,Bahrain,1965,Asia,Western Asia,NaN,692,BHR,NaN,BHR,NaN
747,Bahrain,1966,Asia,Western Asia,NaN,692,BHR,NaN,BHR,NaN
748,Bahrain,1967,Asia,Western Asia,NaN,692,BHR,NaN,BHR,NaN
749,Bahrain,1968,Asia,Western Asia,NaN,692,BHR,NaN,BHR,NaN
750,Bahrain,1969,Asia,Western Asia,NaN,692,BHR,NaN,BHR,NaN
751,Bahrain,1970,Asia,Western Asia,NaN,692,BHR,NaN,BHR,NaN
853,Barbados,1958,Americas,Caribbean,NaN,53,BRB,NaN,BRB,NaN
854,Barbados,1959,Americas,Caribbean,NaN,53,BRB,NaN,BRB,NaN
855,Barbados,1960,Americas,Caribbean,NaN,53,BRB,NaN,BRB,NaN
856,Barbados,1961,Americas,Caribbean,NaN,53,BRB,NaN,BRB,NaN
857,Barbados,1962,Americas,Caribbean,NaN,53,BRB,NaN,BRB,NaN
858,Barbados,1963,Americas,Caribbean,NaN,53,BRB,NaN,BRB,NaN
859,Barbados,1964,Americas,Caribbean,NaN,53,BRB,NaN,BRB,NaN
860,Barbados,1965,Americas,Caribbean,NaN,53,BRB,NaN,BRB,NaN
861,Barbados,1946,Americas,Caribbean,NaN,53,BRB,NaN,BRB,NaN
862,Barbados,1947,Americas,Caribbean,NaN,53,BRB,NaN,BRB,NaN
863,Barbados,1948,Americas,Caribbean,NaN,53,BRB,NaN,BRB,NaN
864,Barbados,1949,Americas,Caribbean,NaN,53,BRB,NaN,BRB,NaN
865,Barbados,1950,Americas,Caribbean,NaN,53,BRB,NaN,BRB,NaN
866,Barbados,1951,Americas,Caribbean,NaN,53,BRB,NaN,BRB,NaN
867,Barbados,1952,Americas,Caribbean,NaN,53,BRB,NaN,BRB,NaN
868,Barbados,1953,Americas,Caribbean,NaN,53,BRB,NaN,BRB,NaN
869,Barbados,1954,Americas,Caribbean,NaN,53,BRB,NaN,BRB,NaN
870,Barbados,1955,Americas,Caribbean,NaN,53,BRB,NaN,BRB,NaN
871,Barbados,1956,Americas,Caribbean,NaN,53,BRB,NaN,BRB,NaN
872,Barbados,1957,Americas,Caribbean,NaN,53,BRB,NaN,BRB,NaN
901,Belarus,1990,Europe,Eastern Europe,NaN,370,BLR,NaN,BLR,NaN
1072,Benin,1946,Africa,Western Africa,NaN,434,BEN,NaN,BEN,NaN
1073,Benin,1947,Africa,Western Africa,NaN,434,BEN,NaN,BEN,NaN
1074,Benin,1948,Africa,Western Africa,NaN,434,BEN,NaN,BEN,NaN
1075,Benin,1949,Africa,Western Africa,NaN,434,BEN,NaN,BEN,NaN
1076,Benin,1950,Africa,Western Africa,NaN,434,BEN,NaN,BEN,NaN
1077,Benin,1951,Africa,Western Africa,NaN,434,BEN,NaN,BEN,NaN
1078,Benin,1952,Africa,Western Africa,NaN,434,BEN,NaN,BEN,NaN

removing rows where both CoW ID is NA and G&W ID should have been NA

In [59]:
cc_check_gw = cc_check_gw[~((cc_check_gw['in_gw'].isna()) & (cc_check_gw['cown'].isna()))]
cc_check_gw

,country.name.en,year,continent,region,cown,gwn,iso3c,p4n,wb,in_gw
0,Afghanistan,1946,Asia,Southern Asia,700,700,AFG,700,AFG,1.0
1,Afghanistan,1947,Asia,Southern Asia,700,700,AFG,700,AFG,1.0
2,Afghanistan,1948,Asia,Southern Asia,700,700,AFG,700,AFG,1.0
3,Afghanistan,1949,Asia,Southern Asia,700,700,AFG,700,AFG,1.0
4,Afghanistan,1950,Asia,Southern Asia,700,700,AFG,700,AFG,1.0
...,...,...,...,...,...,...,...,...,...,...
12847,NaN,1971,NaN,NaN,NaN,990,NaN,NaN,NaN,1.0
12848,NaN,1972,NaN,NaN,NaN,990,NaN,NaN,NaN,1.0
12849,NaN,1973,NaN,NaN,NaN,990,NaN,NaN,NaN,1.0
12850,NaN,1974,NaN,NaN,NaN,990,NaN,NaN,NaN,1.0
12851,NaN,1975,NaN,NaN,NaN,990,NaN,NaN,NaN,1.0

drop rows that were added by the GW merge

In [60]:
cc_clean = cc_check_gw.dropna(subset=['country.name.en'])
cc_clean = cc_clean.sort_values(by=['country.name.en', 'year']).reset_index(drop=True).drop(columns=['in_gw'])
cc_clean = cc_clean.rename(columns={'country.name.en': 'country_name', 'cown': 'cow_id', 'gwn': 'gw_id', 'iso3c': 'iso3alpha', 'p4n': 'p4_id', 'wb': 'wb_id'})
cc_clean

,country_name,year,continent,region,cow_id,gw_id,iso3alpha,p4_id,wb_id
0,Afghanistan,1946,Asia,Southern Asia,700,700,AFG,700,AFG
1,Afghanistan,1947,Asia,Southern Asia,700,700,AFG,700,AFG
2,Afghanistan,1948,Asia,Southern Asia,700,700,AFG,700,AFG
3,Afghanistan,1949,Asia,Southern Asia,700,700,AFG,700,AFG
4,Afghanistan,1950,Asia,Southern Asia,700,700,AFG,700,AFG
...,...,...,...,...,...,...,...,...,...
10964,Zimbabwe,2014,Africa,Eastern Africa,552,552,ZWE,552,ZWE
10965,Zimbabwe,2015,Africa,Eastern Africa,552,552,ZWE,552,ZWE
10966,Zimbabwe,2016,Africa,Eastern Africa,552,552,ZWE,552,ZWE
10967,Zimbabwe,2017,Africa,Eastern Africa,552,552,ZWE,552,ZWE
10968,Zimbabwe,2018,Africa,Eastern Africa,552,552,ZWE,552,ZWE

### Compare to CoW base time series

In [ ]:
cow_ts = cow_ts.rename(columns={'ccode':'cow_id'})
cow_ts = cow_ts[cow_ts['year']>1945]
cow_ts['inCoW'] = 1
cc_check_cow = cc_clean.merge(cow_ts, on=['cow_id', 'year'], how='outer')
cc_check_cow

BOOKMARK HERE

In [61]:
cc_clean.duplicated(subset=['year', 'country_name']).sum()

0

'year' + 'country_name' is the primary key

In [62]:
cc_clean.to_csv("../Data/FINAL/countrycodes_ts-base.csv", index=False, encoding='utf-8')