## Explore and Resolve Discrepancies in State Identifiers

In [1]:
import pandas as pd

In [20]:
cshapes = pd.read_csv("../Data/CShapes/country_shapes.csv", na_values=[-1])
cow = pd.read_csv("../Data/CoW/Raw/states2016.csv")
polity17 = pd.read_csv("../Data/PolityIV/p4v2017d.csv", usecols = ['ccode', 'scode', 'country'])
polity18 = pd.read_csv("../Data/PolityIV/p4v2018.csv", usecols = ['ccode', 'scode', 'country'])
prio = pd.read_csv("../Data/UCDP_PRIO/ucdpprio_armedconflict_api.csv", usecols = ['gwno_a', 'gwno_a_2nd', 'gwno_b', 'gwno_b_2nd', 'side_a', 'side_a_2nd', 'side_a_id', 'side_b', 'side_b_2nd', 'side_b_id'])
wb = pd.read_csv("../Data/WorldBank/countries_list.csv")

In [21]:
cshapes['cow_edate'] = pd.to_datetime(cshapes.cow_endyear*10000+cshapes.cow_endmonth*100+cshapes.cow_endday,format='%Y%m%d')
cshapes['cow_sdate'] = pd.to_datetime(cshapes.cow_startyear*10000+cshapes.cow_startmonth*100+cshapes.cow_startday,format='%Y%m%d')
cshapes['gw_edate'] = pd.to_datetime(cshapes.gw_endyear*10000+cshapes.gw_endmonth*100+cshapes.gw_endday,format='%Y%m%d')
cshapes['gw_sdate'] = pd.to_datetime(cshapes.gw_startyear*10000+cshapes.gw_startmonth*100+cshapes.gw_startday,format='%Y%m%d')

cshapes = cshapes.drop(columns=['area', 'capital_lat', 'capital_long', 'capital_name', 
                                'cow_endyear', 'cow_endmonth', 'cow_endday', 'cow_startyear', 'cow_startmonth', 'cow_startday',
                                'gw_endyear', 'gw_endmonth', 'gw_endday', 'gw_startyear', 'gw_startmonth', 'gw_startday'])
cshapes

,country_name,cow_code,feature_id,gw_code,iso_alpha2,iso_alpha3,iso_name,iso_num,cow_edate,cow_sdate,gw_edate,gw_sdate
0,Guyana,110.0,0,110.0,GY,GUY,Guyana,328,2016-06-30,1966-05-26,2016-06-30,1966-05-26
1,Suriname,115.0,1,115.0,SR,SUR,Suriname,740,2016-06-30,1975-11-25,2016-06-30,1975-11-25
2,Trinidad and Tobago,52.0,2,52.0,TT,TTO,Trinidad and Tobago,780,2016-06-30,1962-08-31,2016-06-30,1962-08-31
3,Venezuela,101.0,3,101.0,VE,VEN,Venezuela,862,2016-06-30,1946-01-01,2016-06-30,1946-01-01
4,Samoa,990.0,4,990.0,WS,WSM,Samoa,882,2016-06-30,1976-12-15,2016-06-30,1962-01-01
5,Tonga,955.0,5,972.0,TO,TON,Tonga,776,2016-06-30,1999-09-14,2016-06-30,1970-06-04
6,Argentina,160.0,6,160.0,AR,ARG,Argentina,32,2016-06-30,1946-01-01,2016-06-30,1946-01-01
7,Bolivia,145.0,7,145.0,BO,BOL,Bolivia,68,2016-06-30,1946-01-01,2016-06-30,1946-01-01
8,Brazil,140.0,8,140.0,BR,BRA,Brazil,76,2016-06-30,1960-04-21,2016-06-30,1960-04-21
9,Chile,155.0,9,155.0,CL,CHL,Chile,152,2016-06-30,1946-01-01,2016-06-30,1946-01-01
10,Ecuador,130.0,10,130.0,EC,ECU,Ecuador,218,2016-06-30,1946-01-01,2016-06-30,1946-01-01
11,Paraguay,150.0,11,150.0,PY,PRY,Paraguay,600,2016-06-30,1946-01-01,2016-06-30,1946-01-01
12,Peru,135.0,12,135.0,PE,PER,Peru,604,2016-06-30,1946-01-01,2016-06-30,1946-01-01
13,Uruguay,165.0,13,165.0,UY,URY,Uruguay,858,2016-06-30,1946-01-01,2016-06-30,1946-01-01
14,Canada,20.0,14,20.0,NaN,NaN,NaN,0,1948-06-30,1946-01-01,1948-06-30,1946-01-01
15,Guatemala,90.0,15,90.0,GT,GTM,Guatemala,320,2016-06-30,1946-01-01,2016-06-30,1946-01-01
16,Mexico,70.0,16,70.0,MX,MEX,Mexico,484,2016-06-30,1946-01-01,2016-06-30,1946-01-01
17,Barbados,53.0,17,53.0,BB,BRB,Barbados,52,2016-06-30,1966-11-30,2016-06-30,1966-11-30
18,Dominica,54.0,18,54.0,DM,DMA,Dominica,212,2016-06-30,1978-11-03,2016-06-30,1978-11-03
19,Grenada,55.0,19,55.0,GD,GRD,Grenada,308,2016-06-30,1974-02-07,2016-06-30,1974-02-07
20,St. Lucia,56.0,20,56.0,LC,LCA,Saint Lucia,662,2016-06-30,1979-02-22,2016-06-30,1979-02-22
21,St. Vincent and the Grenadines,57.0,21,57.0,VC,VCT,Saint Vincent and the Grenadines,670,2016-06-30,1979-10-27,2016-06-30,1979-10-27
22,Dominican Republic,42.0,22,42.0,DO,DOM,Dominican Republic,214,2016-06-30,1946-01-01,2016-06-30,1946-01-01
23,Haiti,41.0,23,41.0,HT,HTI,Haiti,332,2016-06-30,1946-01-01,2016-06-30,1946-01-01
24,Jamaica,51.0,24,51.0,JM,JAM,Jamaica,388,2016-06-30,1962-08-06,2016-06-30,1962-08-06
25,Bahamas,31.0,25,31.0,BS,BHS,Bahamas,44,2016-06-30,1973-07-10,2016-06-30,1973-07-10
26,Belize,80.0,26,80.0,BZ,BLZ,Belize,84,2016-06-30,1981-09-21,2016-06-30,1981-09-21
27,Colombia,100.0,27,100.0,CO,COL,Colombia,170,2016-06-30,1946-01-01,2016-06-30,1946-01-01
28,Costa Rica,94.0,28,94.0,CR,CRI,Costa Rica,188,2016-06-30,1946-01-01,2016-06-30,1946-01-01
29,Cuba,40.0,29,40.0,CU,CUB,Cuba,192,2016-06-30,1946-01-01,2016-06-30,1946-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...
225,Yugoslavia,345.0,230,NaN,YU,YUG,"Yugoslavia, Socialist Federal Republic of",890,1992-04-06,1992-01-15,NaT,NaT
226,Serbia and Montenegro,345.0,231,345.0,CS,SCG,Serbia and Montenegro,891,2006-06-11,1993-04-08,2006-06-02,1992-04-27
227,USSR,365.0,232,NaN,SU,SUN,Union of Soviet Socialist Republics,810,1991-12-25,1991-09-06,NaT,NaT
228,Yugoslavia,345.0,233,NaN,YU,YUG,"Yugoslavia, Socialist Federal Republic of",890,1993-04-07,1992-04-07,NaT,NaT
229,Serbia,345.0,234,340.0,RS,SRB,Serbia,688,2008-02-19,2006-06-12,2008-02-16,2006-06-03
230,Montenegro,341.0,235,341.0,ME,MNE,Montenegro,499,2016-06-30,2006-06-12,2016-06-30,2006-06-03
231,Kosovo,347.0,236,347.0,NaN,NaN,NaN,0,2016-06-30,2008-02-20,2016-06-30,2008-02-17
232,Serbia,345.0,237,340.0,RS,SRB,Serbia,688,2016-06-30,2008-02-20,2016-06-30,2008-02-17
233,United States,2.0,238,2.0,US,USA,United States,840,2016-06-30,1946-01-01,2016-06-30,1946-01-01
234,Uganda,500.0,59,500.0,UG,UGA,Uganda,800,2016-06-30,1962-10-09,2016-06-30,1962-10-09
235,Tanzania,510.0,159,510.0,TZ,TZA,"Tanzania, United Republic of",834,1996-01-31,1964-04-01,1996-01-31,1964-04-01
236,Kenya,501.0,157,501.0,KE,KEN,Kenya,404,2016-06-30,1963-12-12,2016-06-30,1963-12-12
237,Tanzania,510.0,193,510.0,NaN,NaN,NaN,0,1964-03-31,1961-12-09,1964-03-31,1961-12-09
238,Saudi Arabia,670.0,239,670.0,SA,SAU,Saudi Arabia,682,2000-06-11,1946-01-01,2000-06-11,1946-01-01
239,Yemen,679.0,240,678.0,YE,YEM,Yemen,887,2000-06-11,1990-05-22,2000-06-11,1990-05-22
240,Brazil,140.0,241,140.0,NaN,NaN,NaN,0,1960-04-20,1946-01-01,1960-04-20,1946-01-01
241,Tanzania,510.0,242,510.0,TZ,TZA,"Tanzania, United Republic of",834,2016-06-30,1996-02-01,2016-06-30,1996-02-01
242,Morocco,600.0,243,600.0,MA,MAR,Morocco,504,2016-06-30,1979-08-05,2016-06-30,1979-08-05
243,Mauritania,435.0,244,435.0,MR,MRT,Mauritania,478,2016-06-30,1979-08-05,2016-06-30,1979-08-05
244,Sudan,625.0,245,625.0,SD,SDN,Sudan,729,2016-06-30,2011-07-09,2016-06-30,2011-07-09
245,South Sudan,626.0,246,626.0,SS,SSD,South Sudan,728,2016-06-30,2011-07-09,2016-06-30,2011-07-09
246,Yugoslavia,NaN,247,345.0,YU,YUG,"Yugoslavia, Socialist Federal Republic of",890,NaT,NaT,1992-04-26,1991-11-20
247,USSR,NaN,249,365.0,SU,SUN,Union of Soviet Socialist Republics,810,NaT,NaT,1991-08-26,1991-08-25
248,USSR,NaN,250,365.0,SU,SUN,Union of Soviet Socialist Republics,810,NaT,NaT,1991-08-30,1991-08-27
249,USSR,NaN,251,365.0,SU,SUN,Union of Soviet Socialist Republics,810,NaT,NaT,1991-09-05,1991-08-31
250,USSR,NaN,252,365.0,SU,SUN,Union of Soviet Socialist Republics,810,NaT,NaT,1991-09-08,1991-09-06
251,USSR,NaN,253,365.0,SU,SUN,Union of Soviet Socialist Republics,810,NaT,NaT,1991-10-26,1991-09-09
252,USSR,NaN,254,365.0,SU,SUN,Union of Soviet Socialist Republics,810,NaT,NaT,1991-11-30,1991-10-27
253,USSR,NaN,255,365.0,SU,SUN,Union of Soviet Socialist Republics,810,NaT,NaT,1991-12-15,1991-12-01
254,USSR,NaN,256,365.0,SU,SUN,Union of Soviet Socialist Republics,810,NaT,NaT,1991-12-20,1991-12-16

In [30]:
cow['sdate'] = pd.to_datetime(cow.styear*10000+cow.stmonth*100+cow.stday,format='%Y%m%d')
cow['edate'] = pd.to_datetime(cow.endyear*10000+cow.endmonth*100+cow.endday,format='%Y%m%d')

cow = cow.drop(columns=['styear', 'stmonth', 'stday', 'endyear', 'endmonth', 'endday', 'version'])

cow

    stateabb  ccode                        statenme      sdate      edate
0        USA      2        United States of America 1816-01-01 2016-12-31
1        CAN     20                          Canada 1920-01-10 2016-12-31
2        BHM     31                         Bahamas 1973-07-10 2016-12-31
3        CUB     40                            Cuba 1902-05-20 1906-09-25
4        CUB     40                            Cuba 1909-01-23 2016-12-31
5        HAI     41                           Haiti 1859-01-01 1915-07-28
6        HAI     41                           Haiti 1934-08-15 2016-12-31
7        DOM     42              Dominican Republic 1894-01-01 1916-11-29
8        DOM     42              Dominican Republic 1924-09-29 2016-12-31
9        JAM     51                         Jamaica 1962-08-06 2016-12-31
10       TRI     52             Trinidad and Tobago 1962-08-31 2016-12-31
11       BAR     53                        Barbados 1966-11-30 2016-12-31
12       DMA     54                        Dominica 1978-11-03 2016-12-31
13       GRN     55                         Grenada 1974-02-07 2016-12-31
14       SLU     56                       St. Lucia 1979-02-22 2016-12-31
15       SVG     57  St. Vincent and the Grenadines 1979-10-27 2016-12-31
16       AAB     58               Antigua & Barbuda 1981-11-01 2016-12-31
17       SKN     60             St. Kitts and Nevis 1983-09-19 2016-12-31
18       MEX     70                          Mexico 1831-01-01 2016-12-31
19       BLZ     80                          Belize 1981-09-21 2016-12-31
20       GUA     90                       Guatemala 1868-01-01 2016-12-31
21       HON     91                        Honduras 1899-01-01 2016-12-31
22       SAL     92                     El Salvador 1875-01-01 2016-12-31
23       NIC     93                       Nicaragua 1900-01-01 2016-12-31
24       COS     94                      Costa Rica 1920-01-01 2016-12-31
25       PAN     95                          Panama 1903-11-03 2016-12-31
26       COL    100                        Colombia 1831-01-01 2016-12-31
27       VEN    101                       Venezuela 1841-01-01 2016-12-31
28       GUY    110                          Guyana 1966-05-26 2016-12-31
29       SUR    115                        Suriname 1975-11-25 2016-12-31
..       ...    ...                             ...        ...        ...
213      BNG    771                      Bangladesh 1971-12-16 2016-12-31
214      MYA    775                         Myanmar 1948-01-04 2016-12-31
215      SRI    780                       Sri Lanka 1948-02-04 2016-12-31
216      MAD    781                        Maldives 1965-07-26 2016-12-31
217      NEP    790                           Nepal 1920-01-01 2016-12-31
218      THI    800                        Thailand 1887-01-01 2016-12-31
219      CAM    811                        Cambodia 1953-11-09 2016-12-31
220      LAO    812                            Laos 1953-10-23 2016-12-31
221      DRV    816                         Vietnam 1954-07-21 2016-12-31
222      RVN    817             Republic of Vietnam 1954-06-04 1975-04-30
223      MAL    820                        Malaysia 1957-08-31 2016-12-31
224      SIN    830                       Singapore 1965-08-09 2016-12-31
225      BRU    835                          Brunei 1984-01-01 2016-12-31
226      PHI    840                     Philippines 1946-07-04 2016-12-31
227      INS    850                       Indonesia 1949-12-27 2016-12-31
228      ETM    860                      East Timor 2002-09-27 2016-12-31
229      AUL    900                       Australia 1920-01-10 2016-12-31
230      PNG    910                Papua New Guinea 1975-09-16 2016-12-31
231      NEW    920                     New Zealand 1920-01-10 2016-12-31
232      VAN    935                         Vanuatu 1981-09-15 2016-12-31
233      SOL    940                 Solomon Islands 1978-07-07 2016-12-31
234      KIR    946                        Kiribati 1999-09-14 2016-12-31
235      TUV    947                          Tuvalu 2000-09-05 2016-12-31
236      FIJ    950                            Fiji 1970-10-10 2016-12-31
237      TON    955                           Tonga 1999-09-14 2016-12-31
238      NAU    970                           Nauru 1999-09-14 2016-12-31
239      MSI    983                Marshall Islands 1991-09-17 2016-12-31
240      PAL    986                           Palau 1994-12-15 2016-12-31
241      FSM    987  Federated States of Micronesia 1991-09-17 2016-12-31
242      WSM    990                           Samoa 1976-12-15 2016-12-31

[243 rows x 5 columns]

In [31]:
prio

,gwno_a,gwno_a_2nd,gwno_b,gwno_b_2nd,side_a,side_a_2nd,side_a_id,side_b,side_b_2nd,side_b_id
0,145,NaN,NaN,NaN,Government of Bolivia,NaN,23,Popular Revolutionary Movement,NaN,719
1,145,NaN,NaN,NaN,Government of Bolivia,NaN,23,MNR,NaN,720
2,145,NaN,NaN,NaN,Government of Bolivia,NaN,23,ELN,NaN,721
3,220,NaN,NaN,NaN,Government of France,NaN,33,Khmer Issarak,NaN,160
4,220,NaN,NaN,NaN,Government of France,NaN,33,Khmer Issarak,NaN,160
5,220,NaN,NaN,NaN,Government of France,NaN,33,Khmer Issarak,NaN,160
6,220,NaN,NaN,NaN,Government of France,NaN,33,Khmer Issarak,NaN,160
7,220,NaN,NaN,NaN,Government of France,NaN,33,Khmer Issarak,NaN,160
8,220,NaN,NaN,NaN,Government of France,NaN,33,Khmer Issarak,NaN,160
9,220,NaN,NaN,NaN,Government of France,NaN,33,Khmer Issarak,NaN,160
10,220,NaN,NaN,NaN,Government of France,NaN,33,Khmer Issarak,NaN,160
11,710,NaN,NaN,NaN,Government of China,NaN,135,PLA,NaN,161
12,710,NaN,NaN,NaN,Government of China,NaN,135,PLA,NaN,161
13,710,NaN,NaN,NaN,Government of China,NaN,135,PLA,NaN,161
14,710,NaN,NaN,NaN,Government of China,NaN,135,PLA,NaN,161
15,350,NaN,NaN,NaN,Government of Greece,NaN,52,DSE,NaN,162
16,350,NaN,NaN,NaN,Government of Greece,NaN,52,DSE,NaN,162
17,350,NaN,NaN,NaN,Government of Greece,NaN,52,DSE,NaN,162
18,350,NaN,NaN,NaN,Government of Greece,NaN,52,DSE,NaN,162
19,210,NaN,NaN,NaN,Government of Netherlands,NaN,30,Indonesian People's Army,NaN,163
20,210,NaN,NaN,NaN,Government of Netherlands,NaN,30,Indonesian People's Army,NaN,163
21,210,NaN,NaN,NaN,Government of Netherlands,NaN,30,Indonesian People's Army,NaN,163
22,210,NaN,NaN,NaN,Government of Netherlands,NaN,30,Indonesian People's Army,NaN,163
23,630,NaN,NaN,365,Government of Iran,NaN,114,KDPI,Government of Russia (Soviet Union),164
24,630,NaN,NaN,NaN,Government of Iran,NaN,114,KDPI,NaN,164
25,630,NaN,NaN,NaN,Government of Iran,NaN,114,KDPI,NaN,164
26,630,NaN,NaN,NaN,Government of Iran,NaN,114,KDPI,NaN,164
27,630,NaN,NaN,NaN,Government of Iran,NaN,114,KDPI,NaN,164
28,630,NaN,NaN,NaN,Government of Iran,NaN,114,KDPI,NaN,164
29,630,NaN,NaN,NaN,Government of Iran,NaN,114,KDPI,NaN,164
...,...,...,...,...,...,...,...,...,...,...
2354,771,NaN,NaN,NaN,Government of Bangladesh,NaN,143,IS,NaN,234
2355,660,NaN,NaN,NaN,Government of Lebanon,NaN,119,IS,NaN,234
2356,660,NaN,NaN,NaN,Government of Lebanon,NaN,119,IS,NaN,234
2357,660,NaN,NaN,NaN,Government of Lebanon,NaN,119,IS,NaN,234
2358,700,NaN,"2, 200",NaN,Government of Afghanistan,NaN,130,"Government of United Kingdom, Government of Un...",NaN,"28, 3"
2359,620,NaN,NaN,NaN,Government of Libya,NaN,111,IS,NaN,234
2360,620,2,NaN,NaN,Government of Libya,Government of United States of America,111,IS,NaN,234
2361,620,2,NaN,NaN,Government of Libya,Government of United States of America,111,IS,NaN,234
2362,620,2,NaN,NaN,Government of Libya,Government of United States of America,111,IS,NaN,234
2363,615,NaN,NaN,NaN,Government of Algeria,NaN,109,IS,NaN,234
2364,652,NaN,NaN,NaN,Government of Syria,NaN,118,SDF,NaN,6288
2365,652,NaN,NaN,NaN,Government of Syria,NaN,118,SDF,NaN,6288
2366,663,NaN,NaN,NaN,Government of Jordan,NaN,120,IS,NaN,234
2367,640,NaN,NaN,NaN,Government of Turkey,NaN,115,IS,NaN,234
2368,640,NaN,NaN,NaN,Government of Turkey,NaN,115,IS,NaN,234
2369,640,NaN,NaN,NaN,Government of Turkey,NaN,115,IS,NaN,234
2370,770,NaN,NaN,NaN,Government of Pakistan,NaN,142,IS,NaN,234
2371,770,NaN,NaN,NaN,Government of Pakistan,NaN,142,IS,NaN,234
2372,770,NaN,NaN,NaN,Government of Pakistan,NaN,142,IS,NaN,234
2373,520,NaN,NaN,NaN,Government of Somalia,NaN,95,Republic of Somaliland,NaN,675
2374,471,NaN,NaN,NaN,Government of Cameroon,NaN,83,Ambazonia insurgents,NaN,7332
2375,471,NaN,NaN,NaN,Government of Cameroon,NaN,83,Ambazonia insurgents,NaN,7332
2376,630,NaN,NaN,NaN,Government of Iran,NaN,114,IS,NaN,234
2377,840,NaN,NaN,NaN,Government of Philippines,NaN,154,IS,NaN,234
2378,840,NaN,NaN,NaN,Government of Philippines,NaN,154,IS,NaN,234
2379,840,NaN,NaN,NaN,Government of Philippines,NaN,154,IS,NaN,234
2380,616,NaN,NaN,NaN,Government of Tunisia,NaN,110,IS,NaN,234
2381,432,"371, 305, 771, 211, 434, 760, 346, 439, 516, 8...",NaN,NaN,Government of Mali,"Government of Armenia, Government of Austria, ...",72,IS,NaN,234
2382,432,"371, 305, 771, 211, 434, 760, 346, 439, 516, 8...",NaN,NaN,Government of Mali,"Government of Armenia, Government of Austria, ...",72,IS,NaN,234
2383,630,NaN,666,NaN,Government of Iran,NaN,114,Government of Israel,NaN,121